
"""Capability Registry Consolidation for AURA.

Central planner-only registry describing what AURA can do, what is only a
foundation, what is planner-only, what requires permission, what is only a
review/checkpoint layer, and what is still planned for the future.

This registry prepares data for CLI, shell, service monitor, launcher, and
future AURA Control Center views without enabling runtime behavior, file
operations, command execution, tool execution, network action, UI runtime,
service runtime, or external actions.
"""
from __future__ import annotations

from typing import Any


class CapabilityRegistryManager:
    """Central planner-only capability registry for AURA."""

    name = "capability_registry"
    version = "0.1.0"
    status_name = "online"

    def registry_plan_types(self) -> list[str]:
        return [
            "capability_registry_status",
            "capability_catalog_plan",
            "capability_state_review_plan",
            "permission_requirement_review_plan",
            "risk_level_review_plan",
            "control_center_capability_view_plan",
            "capability_gap_review_plan",
            "capability_registry_migration_plan",
            "capability_registry_context",
        ]

    def capability_states(self) -> list[str]:
        return [
            "online",
            "foundation_only",
            "planner_only",
            "permission_gated",
            "review_only",
            "planned_future",
            "disabled_runtime",
        ]

    def risk_levels(self) -> list[str]:
        return [
            "low",
            "medium",
            "high",
            "critical",
        ]

    def permission_categories(self) -> list[str]:
        return [
            "none",
            "read_project",
            "user_confirmation",
            "microphone_permission",
            "camera_permission",
            "screen_permission",
            "file_write_permission",
            "command_execution_permission",
            "dependency_download_permission",
            "internet_search_permission",
            "desktop_control_permission",
            "git_operation_permission",
        ]

    def safe_current_capabilities(self) -> list[str]:
        return [
            "List AURA capabilities as metadata.",
            "Classify capabilities by current state.",
            "Classify capabilities by runtime level.",
            "Classify capabilities by risk level.",
            "List required permission categories.",
            "Identify planned future capabilities without enabling them.",
            "Prepare capability data for future AURA Control Center views.",
            "Keep the registry planner-only, metadata-only, and side-effect-free.",
        ]

    def disabled_capabilities(self) -> list[str]:
        return [
            "runtime_behavior_change",
            "automatic_capability_enablement",
            "dynamic_runtime_discovery",
            "runtime_action_activation",
            "permission_grant_runtime",
            "ui_runtime",
            "web_server_runtime",
            "chat_runtime",
            "service_runtime",
            "launcher_runtime",
            "file_read",
            "file_write",
            "file_modify",
            "file_delete",
            "command_execution",
            "test_execution",
            "code_execution",
            "dependency_install",
            "package_download",
            "internet_search",
            "network_action",
            "tool_execution",
            "real_tool_execution",
            "external_action_execution",
            "memory_write",
            "desktop_control",
            "git_init",
            "git_add",
            "git_commit",
            "git_push",
        ]

    def safety_boundary(self) -> dict[str, bool]:
        return {
            "registry_only": True,
            "planner_only": True,
            "proposal_only": True,
            "metadata_only": True,
            "control_center_data_ready": True,
            "runtime_ready": False,
            "execution_ready": False,
            "executed": False,
            "runtime_behavior_change": False,
            "automatic_capability_enablement": False,
            "dynamic_runtime_discovery": False,
            "runtime_action_activation": False,
            "permission_grant_runtime": False,
            "ui_runtime": False,
            "web_server_runtime": False,
            "chat_runtime": False,
            "service_runtime": False,
            "launcher_runtime": False,
            "file_read": False,
            "file_write": False,
            "file_modify": False,
            "file_delete": False,
            "command_execution": False,
            "test_execution": False,
            "code_execution": False,
            "dependency_install": False,
            "package_download": False,
            "internet_search": False,
            "network_action": False,
            "tool_execution": False,
            "real_tool_execution": False,
            "external_action_execution": False,
            "memory_write": False,
            "desktop_control": False,
            "git_init": False,
            "git_add": False,
            "git_commit": False,
            "git_push": False,
        }

    def capability_catalog(self) -> list[dict[str, Any]]:
        return [
            {
                "id": "thought_loop_planner",
                "name": "Thought Loop Planner",
                "state": "online",
                "runtime_level": "planner_only",
                "risk_level": "low",
                "permission_required": "read_project",
                "category": "thinking",
                "introduced_in": "0.71.0-genesis",
                "control_center_visible": True,
            },
            {
                "id": "reasoning_context_manager",
                "name": "Reasoning Context Manager",
                "state": "online",
                "runtime_level": "planner_only",
                "risk_level": "low",
                "permission_required": "read_project",
                "category": "reasoning",
                "introduced_in": "0.72.0-genesis",
                "control_center_visible": True,
            },
            {
                "id": "knowledge_uncertainty_internet_search_gate",
                "name": "Knowledge Uncertainty & Internet Search Gate",
                "state": "online",
                "runtime_level": "permission_gated_planner",
                "risk_level": "medium",
                "permission_required": "internet_search_permission",
                "category": "knowledge_safety",
                "introduced_in": "0.73.0-genesis",
                "control_center_visible": True,
            },
            {
                "id": "voice_input_runtime_foundation",
                "name": "Voice Input Runtime Foundation",
                "state": "online",
                "runtime_level": "foundation_only",
                "risk_level": "high",
                "permission_required": "microphone_permission",
                "category": "hearing_foundation",
                "introduced_in": "0.74.0-genesis",
                "control_center_visible": True,
            },
            {
                "id": "voice_intent_understanding_layer",
                "name": "Voice Intent Understanding Layer",
                "state": "online",
                "runtime_level": "planner_only",
                "risk_level": "medium",
                "permission_required": "user_confirmation",
                "category": "hearing_understanding",
                "introduced_in": "0.75.0-genesis",
                "control_center_visible": True,
            },
            {
                "id": "vision_input_runtime_foundation",
                "name": "Vision Input Runtime Foundation",
                "state": "online",
                "runtime_level": "foundation_only",
                "risk_level": "high",
                "permission_required": "camera_permission",
                "category": "seeing_foundation",
                "introduced_in": "0.76.0-genesis",
                "control_center_visible": True,
            },
            {
                "id": "visual_context_understanding_layer",
                "name": "Visual Context Understanding Layer",
                "state": "online",
                "runtime_level": "planner_only",
                "risk_level": "high",
                "permission_required": "screen_permission",
                "category": "seeing_understanding",
                "introduced_in": "0.77.0-genesis",
                "control_center_visible": True,
            },
            {
                "id": "coder_project_generation_planner",
                "name": "Coder Project Generation Planner",
                "state": "online",
                "runtime_level": "planner_only",
                "risk_level": "medium",
                "permission_required": "file_write_permission",
                "category": "coding_planner",
                "introduced_in": "0.78.0-genesis",
                "control_center_visible": True,
            },
            {
                "id": "dependency_download_permission_gate",
                "name": "Dependency & Download Permission Gate",
                "state": "online",
                "runtime_level": "permission_gated_planner",
                "risk_level": "high",
                "permission_required": "dependency_download_permission",
                "category": "dependency_safety",
                "introduced_in": "0.79.0-genesis",
                "control_center_visible": True,
            },
            {
                "id": "review_stabilization_71_80",
                "name": "Review & Stabilization 71-80",
                "state": "online",
                "runtime_level": "review_only",
                "risk_level": "low",
                "permission_required": "read_project",
                "category": "checkpoint",
                "introduced_in": "0.80.0-genesis",
                "control_center_visible": True,
            },
            {
                "id": "shared_output_formatter",
                "name": "Shared Output Formatter",
                "state": "online",
                "runtime_level": "foundation_only",
                "risk_level": "low",
                "permission_required": "read_project",
                "category": "output_foundation",
                "introduced_in": "0.81.0-genesis",
                "control_center_visible": True,
            },
            {
                "id": "capability_registry",
                "name": "Capability Registry Consolidation",
                "state": "online",
                "runtime_level": "planner_only",
                "risk_level": "low",
                "permission_required": "read_project",
                "category": "capability_awareness",
                "introduced_in": "0.82.0-genesis",
                "control_center_visible": True,
            },
            {
                "id": "unified_permission_workflow",
                "name": "Unified Permission Workflow Manager",
                "state": "online",
                "runtime_level": "planner_only",
                "risk_level": "high",
                "permission_required": "user_confirmation",
                "category": "permission_workflow",
                "introduced_in": "0.83.0-genesis",
                "control_center_visible": True,
            },
            {
                "id": "aura_runtime_service",
                "name": "AURA Runtime Service Foundation",
                "state": "online",
                "runtime_level": "foundation_only",
                "risk_level": "high",
                "permission_required": "user_confirmation",
                "category": "service_foundation",
                "introduced_in": "0.84.0-genesis",
                "control_center_visible": True,
            },
            {
                "id": "aura_launcher_health_monitor",
                "name": "AURA Launcher & Health Monitor",
                "state": "online",
                "runtime_level": "foundation_only",
                "risk_level": "medium",
                "permission_required": "user_confirmation",
                "category": "operations_monitoring",
                "introduced_in": "0.85.0-genesis",
                "control_center_visible": True,
            },
            {
                "id": "aura_control_center",
                "name": "AURA Control Center",
                "state": "online",
                "runtime_level": "foundation_only",
                "risk_level": "medium",
                "permission_required": "user_confirmation",
                "category": "local_console_ui",
                "introduced_in": "0.86.0-genesis",
                "control_center_visible": True,
            },
            {
                "id": "controlled_file_write_runtime",
                "name": "Controlled File Write Runtime",
                "state": "disabled_runtime",
                "runtime_level": "deferred_runtime",
                "risk_level": "critical",
                "permission_required": "file_write_permission",
                "category": "runtime_action_deferred",
                "introduced_in": "deferred-91-100",
                "control_center_visible": True,
            },
            {
                "id": "controlled_command_execution_runtime",
                "name": "Controlled Command Execution Runtime",
                "state": "disabled_runtime",
                "runtime_level": "deferred_runtime",
                "risk_level": "critical",
                "permission_required": "command_execution_permission",
                "category": "runtime_action_deferred",
                "introduced_in": "deferred-91-100",
                "control_center_visible": True,
            },
                        {
                    "id": "aura_local_console_web_foundation",
                    "name": "AURA Local Console Web Foundation",
                    "state": "online",
                    "runtime_level": "foundation_only",
                    "risk_level": "medium",
                    "permission_required": "user_confirmation",
                    "category": "control_center_web",
                    "introduced_in": "0.87.0-genesis",
                    "control_center_visible": True,
                },
                {
                    "id": "aura_chat_bridge_session_state_foundation",
                    "name": "AURA Chat Bridge & Session State Foundation",
                    "state": "online",
                    "runtime_level": "foundation_only",
                    "risk_level": "medium",
                    "permission_required": "user_confirmation",
                    "category": "chat_bridge",
                    "introduced_in": "0.88.0-genesis",
                    "control_center_visible": True,
                },
                {
                    "id": "aura_plugin_permission_dashboard_foundation",
                    "name": "AURA Plugin / Permission Dashboard Foundation",
                    "state": "online",
                    "runtime_level": "foundation_only",
                    "risk_level": "medium",
                    "permission_required": "user_confirmation",
                    "category": "plugin_permission_dashboard",
                    "introduced_in": "0.89.0-genesis",
                    "control_center_visible": True,
                },
                {
                    "id": "aura_local_console_static_prototype_foundation",
                    "name": "AURA Local Console Static Prototype Foundation",
                    "state": "online",
                    "runtime_level": "foundation_only",
                    "risk_level": "medium",
                    "permission_required": "user_confirmation",
                    "category": "local_console_static_prototype",
                    "introduced_in": "0.91.0-genesis",
                    "control_center_visible": True,
                },
                {
                    "id": "aura_local_console_api_schema_foundation",
                    "name": "AURA Local Console API Schema Foundation",
                    "state": "online",
                    "runtime_level": "foundation_only",
                    "risk_level": "medium",
                    "permission_required": "user_confirmation",
                    "category": "local_console_api_schema",
                    "introduced_in": "0.92.0-genesis",
                    "control_center_visible": True,
                },
                {
                    "id": "aura_control_center_data_aggregator_foundation",
                    "name": "AURA Control Center Data Aggregator Foundation",
                    "state": "online",
                    "runtime_level": "foundation_only",
                    "risk_level": "low",
                    "permission_required": "read_project",
                    "introduced_in": "0.93.0-genesis",
                    "category": "control_center",
                    "control_center_visible": True,
                    "description": "Planner-only Control Center data aggregator foundation for ATLAS core packets, ORION client packets, client bridge packets, dashboard view packets, permission scope packets, health snapshot packets, audit event visibility fields, and metadata-only aggregator safety policy.",
                },
                {
                    "id": "aura_permission_request_review_queue_foundation",
                    "name": "AURA Permission Request Review Queue Foundation",
                    "state": "online",
                    "runtime_level": "foundation_only",
                    "risk_level": "low",
                    "permission_required": "read_project",
                    "introduced_in": "0.94.0-genesis",
                    "category": "permission",
                    "control_center_visible": True,
                    "description": "Planner-only permission request review queue foundation for permission request blueprints, queue state blueprints, review packet fields, scope boundaries, decision proposal contracts, reviewer checklist items, audit visibility fields, and permission request safety policy.",
                },
                {
                    "id": "aura_chat_session_persistence_planner_foundation",
                    "name": "AURA Chat Session Persistence Planner Foundation",
                    "state": "online",
                    "runtime_level": "foundation_only",
                    "risk_level": "low",
                    "permission_required": "read_project",
                    "introduced_in": "0.95.0-genesis",
                    "category": "chat",
                    "control_center_visible": True,
                    "description": "Planner-only chat session persistence planner foundation for session record blueprints, storage boundaries, retention policy blueprints, privacy redaction rules, session lifecycle states, recovery index blueprints, export/migration notes, audit visibility fields, and persistence safety policy.",
                },
                {
                    "id": "aura_safe_local_web_runtime_gate_foundation",
                    "name": "AURA Safe Local Web Runtime Gate Foundation",
                    "state": "online",
                    "runtime_level": "foundation_only",
                    "risk_level": "low",
                    "permission_required": "read_project",
                    "introduced_in": "0.96.0-genesis",
                    "category": "runtime",
                    "control_center_visible": True,
                    "description": "Planner-only and pre-runtime safe local web runtime gate foundation for localhost binding policies, port policies, permission requirements, runtime preflight checks, start/stop proposal contracts, route boundaries, static asset boundaries, kill switch policies, and web runtime audit visibility.",
                },
                {
                    "id": "aura_controlled_file_write_approval_draft_foundation",
                    "name": "AURA Controlled File Write Approval Draft Foundation",
                    "state": "online",
                    "runtime_level": "foundation_only",
                    "risk_level": "medium",
                    "permission_required": "read_project",
                    "introduced_in": "0.97.0-genesis",
                    "category": "file_ops",
                    "control_center_visible": True,
                    "description": "Planner-only and draft-only controlled file write approval foundation for file write proposal drafts, target path policies, diff preview contracts, overwrite rules, backup requirements, approval checklist items, rollback notes, file write audit visibility, and safety policy.",
                },
                {
                    "id": "aura_runtime_action_queue_review_layer_foundation",
                    "name": "AURA Runtime Action Queue Review Layer Foundation",
                    "state": "online",
                    "runtime_level": "foundation_only",
                    "risk_level": "medium",
                    "permission_required": "read_project",
                    "introduced_in": "0.98.0-genesis",
                    "category": "runtime",
                    "control_center_visible": True,
                    "description": "Planner-only, review-only, and proposal-only runtime action queue review layer foundation for action queue item blueprints, queue state blueprints, review priority rules, dependency/blocker contracts, permission link requirements, execution preflight check blueprints, approval/denial transition rules, timeout/expiry policies, runtime action audit visibility, and safety policy.",
                },
                {
                    "id": "aura_pre_runtime_security_audit_foundation",
                    "name": "AURA Pre-Runtime Security Audit Foundation",
                    "state": "online",
                    "runtime_level": "foundation_only",
                    "risk_level": "medium",
                    "permission_required": "read_project",
                    "introduced_in": "0.99.0-genesis",
                    "category": "security",
                    "control_center_visible": True,
                    "description": "Planner-only, review-only, and audit-blueprint-only pre-runtime security audit foundation for audit domains, runtime gate checks, permission boundary checks, file system safety checks, network surface checks, action execution safety checks, ORION boundary checks, audit visibility checks, and Sprint 100 stabilization readiness checks.",
                },
                {
                    "id": "aura_sprint_100_review_stabilization_foundation",
                    "name": "AURA Sprint 100 Review & Stabilization Foundation",
                    "state": "online",
                    "runtime_level": "foundation_only",
                    "risk_level": "medium",
                    "permission_required": "read_project",
                    "introduced_in": "0.100.0-genesis",
                    "category": "stabilization",
                    "control_center_visible": True,
                    "description": "Planner-only, review-only, and checkpoint-blueprint-only Sprint 100 Review & Stabilization Foundation for Sprint 91-100 block review, completed feature inventory, active vs foundation-only boundaries, runtime-zero safety checks, capability registry stabilization, documentation stabilization, unresolved future features, roadmap 101-110 seed planning, and release readiness.",
                },
                {
                    "id": "aura_genesis_runtime_readiness_baseline_foundation",
                    "name": "AURA Genesis Runtime Readiness Baseline Foundation",
                    "state": "online",
                    "runtime_level": "foundation_only",
                    "risk_level": "medium",
                    "permission_required": "read_project",
                    "introduced_in": "0.101.0-genesis",
                    "category": "runtime_readiness",
                    "control_center_visible": True,
                    "description": "Planner-only, metadata-only, and readiness-blueprint-only Genesis Runtime Readiness Baseline Foundation for readiness domains, runtime candidate classification, dry-run prerequisites, permission requirement matrix, safety gate alignment, rollback and kill-switch readiness, audit and observability readiness, rollout phase recommendations, and Sprint 101-110 block alignment.",
                },
                {
                    "id": "aura_safe_runtime_configuration_profile_foundation",
                    "name": "AURA Safe Runtime Configuration Profile Foundation",
                    "state": "online",
                    "runtime_level": "foundation_only",
                    "risk_level": "medium",
                    "permission_required": "read_project",
                    "introduced_in": "0.102.0-genesis",
                    "category": "runtime_readiness",
                    "control_center_visible": True,
                    "description": "Planner-only, metadata-only, and configuration-blueprint-only Safe Runtime Configuration Profile Foundation for profile types, runtime mode policies, service boundaries, permission boundaries, file system boundaries, network boundaries, dry-run requirements, rollout guards, and configuration audit visibility.",
                },
                {
                    "id": "aura_local_service_start_proposal_review_foundation",
                    "name": "AURA Local Service Start Proposal Review Foundation",
                    "state": "online",
                    "runtime_level": "foundation_only",
                    "risk_level": "medium",
                    "permission_required": "read_project",
                    "introduced_in": "0.103.0-genesis",
                    "category": "runtime_readiness",
                    "control_center_visible": True,
                    "description": "Planner-only, metadata-only, and proposal-review-only Local Service Start Proposal Review Foundation for future local service start proposals, service candidates, preflight requirements, port binding review, process launch boundaries, permission requirements, risk classification, rollback/kill-switch planning, audit events, and user approval decisions without starting services or activating runtime.",
                },
                {
                    "id": "aura_dashboard_api_contract_consolidation_foundation",
                    "name": "AURA Dashboard API Contract Consolidation Foundation",
                    "state": "online",
                    "runtime_level": "foundation_only",
                    "risk_level": "medium",
                    "permission_required": "read_project",
                    "introduced_in": "0.104.0-genesis",
                    "category": "runtime_readiness",
                    "control_center_visible": True,
                    "description": "Planner-only, metadata-only, and contract-blueprint-only Dashboard API Contract Consolidation Foundation for API contracts, endpoint schemas, request/response contracts, permission mappings, dashboard payloads, error responses, mock API boundaries, frontend/backend boundaries, and contract validation without starting API runtime.",
                },
                {
                    "id": "aura_permission_decision_runtime_dry_run_foundation",
                    "name": "AURA Permission Decision Runtime Dry-Run Foundation",
                    "state": "online",
                    "runtime_level": "foundation_only",
                    "risk_level": "medium",
                    "permission_required": "read_project",
                    "introduced_in": "0.105.0-genesis",
                    "category": "runtime_readiness",
                    "control_center_visible": True,
                    "description": "Planner-only, metadata-only, and dry-run-blueprint-only Permission Decision Runtime Dry-Run Foundation for permission decision candidates, input contracts, dry-run evaluations, permission scope mappings, approval/denial outcomes, risk review rules, audit record blueprints, dashboard review payloads, and dry-run safety boundaries without changing real permissions.",
                },
                {
                    "id": "aura_runtime_action_execution_preview_packet_foundation",
                    "name": "AURA Runtime Action Execution Preview Packet Foundation",
                    "state": "online",
                    "runtime_level": "foundation_only",
                    "risk_level": "medium",
                    "permission_required": "read_project",
                    "introduced_in": "0.106.0-genesis",
                    "category": "runtime_readiness",
                    "control_center_visible": True,
                    "description": "Planner-only, metadata-only, and preview-packet-only Runtime Action Execution Preview Packet Foundation for action candidates, execution preflight checklists, action input snapshots, permission decision references, execution step previews, side effect boundaries, rollback previews, audit preview records, and user confirmation packets without dispatching or executing runtime actions.",
                },
                {
                    "id": "aura_local_runtime_execution_gate_dry_run_foundation",
                    "name": "AURA Local Runtime Execution Gate Dry-Run Foundation",
                    "state": "online",
                    "runtime_level": "foundation_only",
                    "risk_level": "medium",
                    "permission_required": "read_project",
                    "introduced_in": "0.107.0-genesis",
                    "category": "runtime_readiness",
                    "control_center_visible": True,
                    "description": "Planner-only, metadata-only, and dry-run-gate-blueprint-only Local Runtime Execution Gate Dry-Run Foundation for execution gate candidates, runtime gate input contracts, gate preflight evaluations, safe runtime profile references, permission gate references, execution gate decisions, block reasons, audit gate records, and dashboard gate payloads without opening gates or executing runtime actions.",
                },
                {
                    "id": "aura_runtime_audit_event_packet_preview_foundation",
                    "name": "AURA Runtime Audit Event Packet Preview Foundation",
                    "state": "online",
                    "runtime_level": "foundation_only",
                    "risk_level": "medium",
                    "permission_required": "read_project",
                    "introduced_in": "0.108.0-genesis",
                    "category": "runtime_readiness",
                    "control_center_visible": True,
                    "description": "Planner-only, metadata-only, and audit-packet-preview-only Runtime Audit Event Packet Preview Foundation for audit event candidates, input snapshots, runtime references, permission references, action preview references, audit payload shapes, visibility rules, retention/redaction boundaries, and dashboard audit packets without writing, emitting, streaming, sending, or persisting audit events.",
                },
                {
                    "id": "aura_runtime_safety_freeze_manual_approval_barrier_foundation",
                    "name": "AURA Runtime Safety Freeze Manual Approval Barrier Foundation",
                    "state": "online",
                    "runtime_level": "foundation_only",
                    "risk_level": "medium",
                    "permission_required": "read_project",
                    "introduced_in": "0.109.0-genesis",
                    "category": "runtime_readiness",
                    "control_center_visible": True,
                    "description": "Planner-only, metadata-only, and barrier-blueprint-only Runtime Safety Freeze Manual Approval Barrier Foundation for safety freeze candidates, manual approval barrier inputs, freeze condition checks, approval rules, blocked runtime catalog, user confirmation barriers, emergency stop requirements, audit freeze packet previews, and dashboard barrier payloads without activating freeze, granting approvals, passing barriers, or executing runtime actions.",
                },
                {
                    "id": "aura_review_stabilization_101_110_foundation",
                    "name": "AURA Review Stabilization 101-110 Foundation",
                    "state": "online",
                    "runtime_level": "review_only",
                    "risk_level": "low",
                    "permission_required": "read_project",
                    "introduced_in": "0.110.0-genesis",
                    "category": "stabilization",
                    "control_center_visible": True,
                    "description": "Planner-only, metadata-only, and checkpoint-review-only Review Stabilization 101-110 Foundation for sprint completion inventory, runtime readiness foundation audit, safety invariant verification, capability registry delta review, integration surface review, documentation consistency review, checkpoint risk review, deferred runtime boundary review, and next block readiness without enabling runtime execution.",
                },
                {
                    "id": "aura_genesis_runtime_readiness_next_block_planning_foundation",
                    "name": "AURA Genesis Runtime Readiness Next Block Planning Foundation",
                    "state": "online",
                    "runtime_level": "foundation_only",
                    "risk_level": "low",
                    "permission_required": "read_project",
                    "introduced_in": "0.111.0-genesis",
                    "category": "runtime_readiness",
                    "control_center_visible": True,
                    "description": "Planner-only, metadata-only, and next-block-planning-only Genesis Runtime Readiness Next Block Planning Foundation for Sprint 111-120 candidates, runtime readiness continuity, manual approval evolution, audit event evolution, dashboard contract evolution, ORION boundary planning, safe local action boundary, integration stabilization, and v1 readiness mapping without enabling runtime execution.",
                },
                {
                    "id": "aura_runtime_permission_flow_consolidation_foundation",
                    "name": "AURA Runtime Permission Flow Consolidation Foundation",
                    "state": "online",
                    "runtime_level": "foundation_only",
                    "risk_level": "low",
                    "permission_required": "read_project",
                    "introduced_in": "0.112.0-genesis",
                    "category": "runtime_readiness",
                    "control_center_visible": True,
                    "description": "Planner-only, metadata-only, and permission-flow-consolidation-only Runtime Permission Flow Consolidation Foundation for permission request schema, permission decision states, manual approval checkpoints, denial and cancellation flow, permission scope boundaries, high-risk escalation rules, approval audit references, dashboard permission flow payloads, and future runtime grant boundaries without changing permissions or enabling runtime execution.",
                },
                {
                    "id": "aura_audit_event_review_queue_foundation",
                    "name": "AURA Audit Event Review Queue Foundation",
                    "state": "online",
                    "runtime_level": "foundation_only",
                    "risk_level": "low",
                    "permission_required": "read_project",
                    "introduced_in": "0.113.0-genesis",
                    "category": "audit",
                    "control_center_visible": True,
                    "description": "Planner-only, metadata-only, and review-queue-blueprint-only Audit Event Review Queue Foundation for audit event intake schema, review queue state model, triage rules, permission linkage review, runtime boundary review, redaction visibility review, dashboard review queue payloads, review outcome catalog, and future audit writer boundary without writing, emitting, streaming, sending, or persisting audit events.",
                },
                {
                    "id": "aura_dashboard_runtime_readiness_view_model_foundation",
                    "name": "AURA Dashboard Runtime Readiness View Model Foundation",
                    "state": "online",
                    "runtime_level": "foundation_only",
                    "risk_level": "low",
                    "permission_required": "read_project",
                    "introduced_in": "0.114.0-genesis",
                    "category": "dashboard",
                    "control_center_visible": True,
                    "description": "Planner-only, metadata-only, and view-model-only Dashboard Runtime Readiness View Model Foundation for runtime readiness summary, permission state, audit review queue, safety boundary, ORION boundary, action preview, manual approval, v1 cutline, and Control Center payload views without starting dashboard runtime, API server, web server, frontend/backend runtime, or enabling runtime execution.",
                },
                {
                    "id": "aura_safe_local_action_contract_review_foundation",
                    "name": "AURA Safe Local Action Contract Review Foundation",
                    "state": "online",
                    "runtime_level": "foundation_only",
                    "risk_level": "low",
                    "permission_required": "read_project",
                    "introduced_in": "0.115.0-genesis",
                    "category": "local_action",
                    "control_center_visible": True,
                    "description": "Planner-only, metadata-only, and contract-review-only Safe Local Action Contract Review Foundation for local open contracts, controlled create contracts, controlled write preview contracts, action preview packets, permission scope contracts, side effect boundaries, rollback/cancel contracts, dashboard contract payloads, and future action runtime boundaries without executing local actions or enabling runtime execution.",
                },
                {
                    "id": "aura_orion_client_boundary_contract_foundation",
                    "name": "AURA ORION Client Boundary Contract Foundation",
                    "state": "online",
                    "runtime_level": "foundation_only",
                    "risk_level": "low",
                    "permission_required": "read_project",
                    "introduced_in": "0.116.0-genesis",
                    "category": "orion",
                    "control_center_visible": True,
                    "description": "Planner-only, metadata-only, and boundary-contract-only ORION Client Boundary Contract Foundation for ORION client identity, ATLAS/ORION authority, ORION sense permission, ORION local action, emergency stop, dashboard status payload, runtime handshake, data-flow redaction, and future ORION runtime boundaries without starting ORION client runtime or enabling runtime execution.",
                },
                {
                    "id": "aura_runtime_error_rollback_preview_foundation",
                    "name": "AURA Runtime Error and Rollback Preview Foundation",
                    "state": "online",
                    "runtime_level": "foundation_only",
                    "risk_level": "low",
                    "permission_required": "read_project",
                    "introduced_in": "0.117.0-genesis",
                    "category": "runtime_readiness",
                    "control_center_visible": True,
                    "description": "Planner-only, metadata-only, and preview-only Runtime Error and Rollback Preview Foundation for runtime error taxonomy, rollback preview packets, failure recovery state models, cancellation boundaries, partial execution guards, permission error reviews, audit error references, dashboard error rollback payloads, and future runtime recovery boundaries without executing rollback, recovery, cancellation, or runtime mutation.",
                },
                {
                    "id": "aura_manual_approval_decision_flow_review_foundation",
                    "name": "AURA Manual Approval Decision Flow Review Foundation",
                    "state": "online",
                    "runtime_level": "foundation_only",
                    "risk_level": "low",
                    "permission_required": "read_project",
                    "introduced_in": "0.118.0-genesis",
                    "category": "permission",
                    "control_center_visible": True,
                    "description": "Planner-only, metadata-only, and review-only Manual Approval Decision Flow Review Foundation for approval request schema, decision state, outcome catalog, denial/cancellation, escalation boundary, audit reference, dashboard payload, runtime gate, and future approval runtime boundaries without creating approval requests, persisting approval state, applying approval decisions, changing permission, or enabling runtime execution.",
                },
                {
                    "id": "aura_v1_runtime_readiness_cutline_review_foundation",
                    "name": "AURA v1 Runtime Readiness Cutline Review Foundation",
                    "state": "online",
                    "runtime_level": "foundation_only",
                    "risk_level": "low",
                    "permission_required": "read_project",
                    "introduced_in": "0.119.0-genesis",
                    "category": "runtime_readiness",
                    "control_center_visible": True,
                    "description": "Planner-only, metadata-only, and review-only v1 Runtime Readiness Cutline Review Foundation for allowed capabilities, deferred capabilities, runtime gates, permission/audit requirements, ORION boundaries, dashboard visibility, release blockers, safe idle acceptance, and future v1 runtime activation boundaries without approving v1 runtime, opening release gates, enabling features, or enabling runtime execution.",
                },
                {
                    "id": "aura_review_stabilization_111_120_foundation",
                    "name": "AURA Review Stabilization 111-120 Foundation",
                    "state": "online",
                    "runtime_level": "foundation_only",
                    "risk_level": "low",
                    "permission_required": "read_project",
                    "introduced_in": "0.120.0-genesis",
                    "category": "runtime_readiness",
                    "control_center_visible": True,
                    "description": "Planner-only, metadata-only, and checkpoint-review-only Review Stabilization 111-120 Foundation for Sprint 111-120 completion review, capability registry stabilization, runtime safety zero-state review, integration surface stabilization, documentation roadmap stabilization, v1 blocker review, release cutline consistency, next block 121-130 boundary planning, and checkpoint 120 acceptance review without approving runtime, opening release gates, enabling v1 runtime, mutating capability states, or enabling runtime execution.",
                },
                {
                    "id": "aura_service_audit_link_foundation",
                    "name": "AURA Service Audit Link Foundation",
                    "state": "online",
                    "runtime_level": "foundation_only",
                    "risk_level": "critical",
                    "permission_required": "read_project",
                    "introduced_in": "0.146.0-genesis",
                    "category": "service",
                    "control_center_visible": True,
                    "description": "Planner-only, metadata-only, and foundation-only Service Audit Link Foundation for future service audit event references, audit link contracts, traceability chains, permission/audit pairing, Control Center audit visibility, redaction boundaries, failure safe-idle behavior, retention boundaries, error boundary, and no audit link runtime activation review without creating audit link records, writing audit events, appending audit logs, executing redaction runtime, writing trace chains, starting services, binding ports, executing tools/commands, using file/memory/model/permission/audit/ORION/git runtime, or enabling runtime execution features.",
                },
                {
                    "id": "aura_service_permission_gate_runtime_boundary",
                    "name": "AURA Service Permission Gate Runtime Boundary",
                    "state": "online",
                    "runtime_level": "foundation_only",
                    "risk_level": "critical",
                    "permission_required": "read_project",
                    "introduced_in": "0.145.0-genesis",
                    "category": "service",
                    "control_center_visible": True,
                    "description": "Planner-only, metadata-only, and foundation-only Service Permission Gate Runtime Boundary for future service permission scopes, request contracts, grant preflight, denial safe-idle behavior, Control Center permission visibility, audit linkage, grant expiry review, error boundary, manual approval boundary, and no permission runtime activation review without creating permission requests, applying grants, mutating permissions, writing audit events, starting services, binding ports, executing tools/commands, using file/memory/model/permission/audit/ORION/git runtime, or enabling runtime execution features.",
                },
                {
                    "id": "aura_local_service_configuration_port_registry_foundation",
                    "name": "AURA Service Configuration and Port Registry Foundation",
                    "state": "online",
                    "runtime_level": "foundation_only",
                    "risk_level": "high",
                    "permission_required": "read_project",
                    "introduced_in": "0.144.0-genesis",
                    "category": "service",
                    "control_center_visible": True,
                    "description": "Planner-only, metadata-only, and foundation-only Service Configuration and Port Registry Foundation for future service configuration scope, config schema, port registry schema, localhost port policy, reserved port policy, port conflict preflight, environment override boundary, Control Center config card, permission/audit config linkage, and no config/port runtime activation review without reading or writing runtime configuration, reserving ports, binding ports, opening sockets, starting servers, mutating environment state, writing files, mutating permissions, writing audit events, dispatching actions, executing tools/commands, using file/memory/model/permission/audit/ORION/git runtime, or enabling runtime execution features.",
                },
                {
                    "id": "aura_local_service_health_endpoint_foundation",
                    "name": "AURA Local Service Health Endpoint Foundation",
                    "state": "online",
                    "runtime_level": "foundation_only",
                    "risk_level": "high",
                    "permission_required": "read_project",
                    "introduced_in": "0.143.0-genesis",
                    "category": "service",
                    "control_center_visible": True,
                    "description": "Planner-only, metadata-only, and foundation-only Local Service Health Endpoint Foundation for future localhost-only health endpoint scope, read-only /health contract, health response schema, localhost binding boundary, safe-idle health state, dependency visibility, permission/audit health linkage, Control Center health card, error fallback, and no-health-endpoint-activation review without starting servers, opening sockets, binding ports, serving HTTP, polling networks, writing files, mutating permissions, writing audit events, dispatching actions, executing tools/commands, using file/memory/model/permission/audit/ORION/git runtime, or enabling runtime execution features.",
                },
                {
                    "id": "aura_local_service_safe_idle_boot_boundary",
                    "name": "AURA Local Service Safe Idle Boot Boundary",
                    "state": "online",
                    "runtime_level": "foundation_only",
                    "risk_level": "high",
                    "permission_required": "read_project",
                    "introduced_in": "0.142.0-genesis",
                    "category": "service",
                    "control_center_visible": True,
                    "description": "Planner-only, metadata-only, and foundation-only Local Service Safe Idle Boot Boundary for ATLAS safe-idle boot scope, boot entry state contracts, guard conditions, boot failure fallback, no-autostart boundary, read-only readiness probes, Control Center idle visibility, permission denial idle behavior, audit failure idle behavior, and no-boot-activation review without starting services, autostarting, opening sockets, binding ports, creating or starting systemd units, dispatching actions, executing tools/commands, using file/memory/model/permission/audit/ORION/git runtime, or enabling runtime execution features.",
                },
                {
                    "id": "aura_local_service_runtime_foundation",
                    "name": "AURA Local Service Runtime Foundation",
                    "state": "online",
                    "runtime_level": "foundation_only",
                    "risk_level": "high",
                    "permission_required": "read_project",
                    "introduced_in": "0.141.0-genesis",
                    "category": "service",
                    "control_center_visible": True,
                    "description": "Planner-only, metadata-only, and foundation-only Local Service Runtime Foundation for ATLAS safe-idle service identity, localhost-only boundary, lifecycle state, configuration contract, health surface, permission gate link, audit link, control command boundary, and no-start activation review without starting services, opening sockets, binding ports, creating systemd units, dispatching actions, executing tools/commands, using file/memory/model/permission/audit/ORION/git runtime, or enabling runtime execution features.",
                },
                {
                    "id": "aura_review_stabilization_131_140_foundation",
                    "name": "AURA Review Stabilization 131-140 Foundation",
                    "state": "online",
                    "runtime_level": "foundation_only",
                    "risk_level": "low",
                    "permission_required": "read_project",
                    "introduced_in": "0.140.0-genesis",
                    "category": "stabilization",
                    "control_center_visible": True,
                    "description": "Planner-only, metadata-only, and review-only Review & Stabilization 131-140 Foundation covering Sprint 131-140 scope, runtime boundary integrity, capability registry consistency, system status surfaces, skill/plugin/CLI/shell integration, documentation roadmap state, safety counter zero state, git/boot verification, next block readiness, and no-runtime-activation review without service/API/dashboard/chat/memory/permission/audit/model/action/tool/command/file/port/network/ORION/git runtime or runtime execution features.",
                },
                {
                    "id": "aura_audit_runtime_writer_activation_review_foundation",
                    "name": "AURA Audit Runtime Writer Activation Review Foundation",
                    "state": "online",
                    "runtime_level": "foundation_only",
                    "risk_level": "low",
                    "permission_required": "read_project",
                    "introduced_in": "0.139.0-genesis",
                    "category": "audit",
                    "control_center_visible": True,
                    "description": "Planner-only, metadata-only, and review-only Audit Runtime Writer Activation Review Foundation covering audit writer activation scope, event schema, append-only storage, redaction boundary, actor context, permission links, dashboard visibility, failure safe idle, retention/export, and no-write activation review without starting/stopping audit writers, receiving/writing audit events, appending logs, writing storage, redaction runtime, dashboard event emit, permission mutation, action dispatch, tool/command execution, file/service/port/network/ORION/git runtime, or runtime execution features.",
                },
                {
                    "id": "aura_permission_runtime_grant_gate_review_foundation",
                    "name": "AURA Permission Runtime Grant Gate Review Foundation",
                    "state": "online",
                    "runtime_level": "foundation_only",
                    "risk_level": "low",
                    "permission_required": "read_project",
                    "introduced_in": "0.138.0-genesis",
                    "category": "permission",
                    "control_center_visible": True,
                    "description": "Planner-only, metadata-only, and review-only Permission Runtime Grant Gate Review Foundation covering permission grant scope, manual approval, expiry, denial, audit link, dashboard visibility, revocation, risk classification, safe idle failure, and no-mutation review without receiving runtime permission requests, creating/applying/updating/revoking grants, applying expiry, creating denials, risk classification runtime, audit writer/event runtime, dashboard event emit, action dispatch, tool/command execution, file/service/port/network/ORION/git runtime, or runtime execution features.",
                },
                {
                    "id": "aura_memory_runtime_write_gate_review_foundation",
                    "name": "AURA Memory Runtime Write Gate Review Foundation",
                    "state": "online",
                    "runtime_level": "foundation_only",
                    "risk_level": "low",
                    "permission_required": "read_project",
                    "introduced_in": "0.137.0-genesis",
                    "category": "memory",
                    "control_center_visible": True,
                    "description": "Planner-only, metadata-only, and review-only Memory Runtime Write Gate Review Foundation covering memory write intent classification, manual approval, scope boundary, redaction, conflict resolution, audit event, rollback, safe idle failure, session link, and no-persistence review without reading memory, writing memory, creating/updating/deleting memory records, receiving runtime memory write requests, creating permission grants, starting audit writers, writing audit events, rollback/recovery execution, dashboard event emit, action dispatch, tool/command execution, file/service/port/network/ORION/git runtime, or runtime execution features.",
                },
                {
                    "id": "aura_chat_runtime_minimal_loop_review_foundation",
                    "name": "AURA Chat Runtime Minimal Loop Review Foundation",
                    "state": "online",
                    "runtime_level": "foundation_only",
                    "risk_level": "low",
                    "permission_required": "read_project",
                    "introduced_in": "0.136.0-genesis",
                    "category": "chat",
                    "control_center_visible": True,
                    "description": "Planner-only, metadata-only, and review-only Chat Runtime Minimal Loop Review Foundation covering chat input boundary, response boundary, session state, permission prompts, memory read/write gates, audit events, safe idle fallback, error recovery, manual approval runtime entry, and no-model-execution review without starting chat runtime, receiving or processing runtime messages, generating or sending responses, mutating sessions, reading/writing memory, creating permission prompts, starting audit writers, model request/inference execution, action dispatch, tool/command execution, file/service/port/network/ORION/git runtime, or runtime execution features.",
                },
                {
                    "id": "aura_control_center_runtime_entry_review_foundation",
                    "name": "AURA Control Center Runtime Entry Review Foundation",
                    "state": "online",
                    "runtime_level": "foundation_only",
                    "risk_level": "low",
                    "permission_required": "read_project",
                    "introduced_in": "0.135.0-genesis",
                    "category": "dashboard",
                    "control_center_visible": True,
                    "description": "Planner-only, metadata-only, and review-only Control Center Runtime Entry Review Foundation covering entry route, localhost boundary, read-only default, status panel runtime entry, permission panel runtime entry, audit panel runtime entry, action proposal panel runtime entry, safe idle/error panel runtime entry, manual approval entry, and no-server-start review without creating routes, binding routes, starting Control Center, starting dashboard/API/web/frontend/backend servers, binding ports, starting panels, emitting dashboard events, creating permission grants, starting audit writers, action dispatch, tool/command execution, file/service/network/ORION/git runtime, or runtime execution features.",
                },
                {
                    "id": "aura_local_service_boot_plan_review_foundation",
                    "name": "AURA Local Service Boot Plan Review Foundation",
                    "state": "online",
                    "runtime_level": "foundation_only",
                    "risk_level": "low",
                    "permission_required": "read_project",
                    "introduced_in": "0.134.0-genesis",
                    "category": "runtime",
                    "control_center_visible": True,
                    "description": "Planner-only, metadata-only, and review-only Local Service Boot Plan Review Foundation for ATLAS covering manual start, manual stop, health monitor, safe shutdown, config contract, log visibility, localhost-only behavior, autostart guard, failure safe idle, and no-port-binding review without creating service units, modifying startup configuration, enabling autostart, starting services, binding ports, starting API/web/dashboard/chat/memory/permission/audit runtime, action dispatch, tool/command execution, file/service/network/ORION/git runtime, or runtime execution features.",
                },
                {
                    "id": "aura_runtime_activation_path_proposal_review_foundation",
                    "name": "AURA Runtime Activation Path Proposal Review Foundation",
                    "state": "online",
                    "runtime_level": "foundation_only",
                    "risk_level": "low",
                    "permission_required": "read_project",
                    "introduced_in": "0.133.0-genesis",
                    "category": "runtime",
                    "control_center_visible": True,
                    "description": "Planner-only, metadata-only, and review-only Runtime Activation Path Proposal Review Foundation for runtime activation stage model, manual approval chain, activation blocker register links, permission contract activation, audit contract activation, dashboard visibility activation, safe idle rollback activation, emergency stop activation, release candidate transition, and activation denial/deferment review without applying activation paths, enabling stages, opening runtime gates, starting runtime activation, release candidates, local services, dashboard/chat/memory/permission/audit runtime, blocker mutations, action dispatch, tool/command execution, file/service/network/ORION/git runtime, or runtime execution features.",
                },
                {
                    "id": "aura_final_genesis_acceptance_criteria_foundation",
                    "name": "AURA Final Genesis Acceptance Criteria Foundation",
                    "state": "online",
                    "runtime_level": "foundation_only",
                    "risk_level": "low",
                    "permission_required": "read_project",
                    "introduced_in": "0.132.0-genesis",
                    "category": "planning",
                    "control_center_visible": True,
                    "description": "Planner-only, metadata-only, and review-only Final Genesis Acceptance Criteria Foundation for boot stability, local service, Control Center, local chat, memory, permission/audit, safe idle/recovery, optional ORION/voice/vision/avatar boundaries, Final Genesis go/no-go, and future runtime release candidate criteria without Final Genesis release, release candidate runtime, service boot, dashboard/chat/memory runtime, permission grants, audit writer runtime, action dispatch, tool/command execution, file/service/network/ORION/voice/vision/avatar/streaming/git runtime, or runtime execution features.",
                },
                {
                    "id": "aura_post_checkpoint_130_next_block_foundation",
                    "name": "AURA Post-Checkpoint 130 Next Block Foundation",
                    "state": "online",
                    "runtime_level": "foundation_only",
                    "risk_level": "low",
                    "permission_required": "read_project",
                    "introduced_in": "0.131.0-genesis",
                    "category": "planning",
                    "control_center_visible": True,
                    "description": "Planner-only, metadata-only, and review-only Post-Checkpoint 130 Next Block Foundation for the Sprint 131-140 block toward Final Genesis, including sprint sequence, Final Genesis acceptance criteria direction, runtime activation path proposal, local service boot plan, Control Center runtime entry, chat runtime minimal loop, memory runtime write gate, permission runtime grant gate, audit runtime writer activation, and Sprint 140 stabilization checkpoint without runtime activation, service boot, dashboard/chat/memory runtime, permission grant runtime, audit writer runtime, action dispatch, tool/command execution, file/service/network/ORION/git runtime, or runtime execution features.",
                },
                {
                    "id": "aura_review_stabilization_121_130_foundation",
                    "name": "AURA Review Stabilization 121-130 Foundation",
                    "state": "online",
                    "runtime_level": "review_only",
                    "risk_level": "low",
                    "permission_required": "read_project",
                    "introduced_in": "0.130.0-genesis",
                    "category": "stabilization",
                    "control_center_visible": True,
                    "description": "Review-only Sprint 121-130 stabilization checkpoint for Sprint 121-129 completion, capability registry consistency, permission boundaries, runtime zero counters, dashboard/ORION boundaries, action/permission/recovery/blocker boundaries, documentation and roadmap consistency, boot/CLI surfaces, known deferred runtime, and future Sprint 131-140 readiness without runtime activation, checkpoint mutation, registry mutation, permission change, audit write, dashboard emit, action dispatch, tool/command execution, file/service/network/ORION/memory/git runtime, or runtime execution features.",
                },
                {
                    "id": "aura_runtime_activation_blocker_register_boundary_review_foundation",
                    "name": "AURA Runtime Activation Blocker Register Boundary Review Foundation",
                    "state": "online",
                    "runtime_level": "foundation_only",
                    "risk_level": "low",
                    "permission_required": "read_project",
                    "introduced_in": "0.129.0-genesis",
                    "category": "runtime",
                    "control_center_visible": True,
                    "description": "Planner-only, metadata-only, and review-only Runtime Activation Blocker Register Boundary Review Foundation for blocker register schema, blocker source classification, blocker severity policy, blocker activation gate link, blocker resolution evidence, blocker dashboard visibility, blocker audit link, blocker failure safe idle, and future runtime activation unblock boundaries without creating, updating, deleting, resolving, or unblocking runtime activation blockers; opening runtime gates; activating runtime; writing audit events; emitting dashboard events; dispatching actions; or enabling runtime execution.",
                },
                {
                    "id": "aura_dashboard_runtime_readiness_boundary_review_foundation",
                    "name": "AURA Dashboard Runtime Readiness Boundary Review Foundation",
                    "state": "online",
                    "runtime_level": "foundation_only",
                    "risk_level": "low",
                    "permission_required": "read_project",
                    "introduced_in": "0.128.0-genesis",
                    "category": "dashboard",
                    "control_center_visible": True,
                    "description": "Planner-only, metadata-only, and review-only Dashboard Runtime Readiness Boundary Review Foundation for dashboard runtime entrypoint, route contract, API contract, websocket event, permission panel runtime, audit panel runtime, action panel runtime, failure safe idle, and future dashboard runtime activation boundaries without starting dashboard/web/API/frontend/backend servers, binding ports, opening browsers, registering runtime routes, opening websockets, emitting dashboard events, changing permissions, writing audit events, dispatching actions, or enabling runtime execution.",
                },
                {
                    "id": "aura_runtime_recovery_drill_boundary_review_foundation",
                    "name": "AURA Runtime Recovery Drill Boundary Review Foundation",
                    "state": "online",
                    "runtime_level": "foundation_only",
                    "risk_level": "low",
                    "permission_required": "read_project",
                    "introduced_in": "0.127.0-genesis",
                    "category": "runtime",
                    "control_center_visible": True,
                    "description": "Planner-only, metadata-only, and review-only Runtime Recovery Drill Boundary Review Foundation for recovery drill scenario catalog, recovery trigger, recovery safe idle, rollback preview, recovery audit/dashboard, recovery permission, ORION recovery disconnect, recovery failure escalation, and future runtime recovery drill boundaries without starting recovery drills, executing recovery actions, applying rollback, restarting services, mutating permissions, writing audit events, emitting dashboard events, dispatching actions, or enabling runtime execution.",
                },
                {
                    "id": "aura_runtime_grant_expiry_boundary_review_foundation",
                    "name": "AURA Runtime Grant Expiry Boundary Review Foundation",
                    "state": "online",
                    "runtime_level": "foundation_only",
                    "risk_level": "low",
                    "permission_required": "read_project",
                    "introduced_in": "0.126.0-genesis",
                    "category": "permission",
                    "control_center_visible": True,
                    "description": "Planner-only, metadata-only, and review-only Runtime Grant Expiry Boundary Review Foundation for grant expiry schema, grant lifetime policy, grant renewal request, grant revocation, expired grant denial, dashboard grant visibility, audit grant expiry, grant expiry failure safe idle, and future runtime grant expiry boundaries without creating grants, renewing grants, revoking grants, applying expiry state, mutating permissions, writing audit events, emitting dashboard events, dispatching actions, or enabling runtime execution.",
                },
                {
                    "id": "aura_safe_local_action_allowlist_boundary_review_foundation",
                    "name": "AURA Safe Local Action Allowlist Boundary Review Foundation",
                    "state": "online",
                    "runtime_level": "foundation_only",
                    "risk_level": "low",
                    "permission_required": "read_project",
                    "introduced_in": "0.125.0-genesis",
                    "category": "actions",
                    "control_center_visible": True,
                    "description": "Planner-only, metadata-only, and review-only Safe Local Action Allowlist Boundary Review Foundation for safe action catalog, action scope, permission requirements, risk levels, rollback references, audit/dashboard visibility, denied action policy, runtime gates, and future safe local action runtime boundaries without applying allowlists, creating permission requests, dispatching actions, executing actions, writing audit events, emitting dashboard events, using file runtime, starting services, probing network, performing ORION handshakes, or enabling runtime execution.",
                },
                {
                    "id": "aura_orion_dry_handshake_boundary_review_foundation",
                    "name": "AURA ORION Dry Handshake Boundary Review Foundation",
                    "state": "online",
                    "runtime_level": "foundation_only",
                    "risk_level": "low",
                    "permission_required": "read_project",
                    "introduced_in": "0.124.0-genesis",
                    "category": "orion",
                    "control_center_visible": True,
                    "description": "Planner-only, metadata-only, and review-only ORION Dry Handshake Boundary Review Foundation for client identity packets, capability packets, permission scope packets, status heartbeat, redaction, emergency stop, ATLAS/ORION authority, ORION failure safe idle, and future ORION handshake runtime boundaries without starting ORION client runtime, performing handshakes, sending packets, probing network, emitting dashboard events, changing permissions, or enabling runtime execution.",
                },
                {
                    "id": "aura_dashboard_control_center_boundary_review_foundation",
                    "name": "AURA Dashboard Control Center Boundary Review Foundation",
                    "state": "online",
                    "runtime_level": "foundation_only",
                    "risk_level": "low",
                    "permission_required": "read_project",
                    "introduced_in": "0.123.0-genesis",
                    "category": "dashboard",
                    "control_center_visible": True,
                    "description": "Planner-only, metadata-only, and review-only Dashboard Control Center Boundary Review Foundation for shell layout, status payload, permission panel, audit panel, action proposal panel, ORION client panel, runtime gate panel, dashboard failure safe idle policy, and future dashboard control center runtime boundaries without starting dashboard runtime, starting web/API/frontend/backend services, binding routes or ports, emitting dashboard events, changing permissions, performing ORION handshakes, or enabling runtime execution.",
                },
                {
                    "id": "aura_runtime_permission_audit_writer_boundary_review_foundation",
                    "name": "AURA Runtime Permission Audit Writer Boundary Review Foundation",
                    "state": "online",
                    "runtime_level": "foundation_only",
                    "risk_level": "low",
                    "permission_required": "read_project",
                    "introduced_in": "0.122.0-genesis",
                    "category": "runtime_readiness",
                    "control_center_visible": True,
                    "description": "Planner-only, metadata-only, and review-only Runtime Permission Audit Writer Boundary Review Foundation for schema, storage, redaction, visibility, permission decision links, dashboard audit payloads, failure boundaries, runtime gates, and future permission audit writer runtime boundaries without starting audit writer runtime, writing audit events, persisting audit records, writing audit files, changing permissions, emitting dashboard events, performing ORION handshakes, or enabling runtime execution.",
                },
                {
                    "id": "aura_post_checkpoint_120_next_block_planning_foundation",
                    "name": "AURA Post-Checkpoint 120 Next Block Planning Foundation",
                    "state": "online",
                    "runtime_level": "foundation_only",
                    "risk_level": "low",
                    "permission_required": "read_project",
                    "introduced_in": "0.121.0-genesis",
                    "category": "runtime_readiness",
                    "control_center_visible": True,
                    "description": "Planner-only, metadata-only, and review-only Post-Checkpoint 120 Next Block Planning Foundation for checkpoint 120 output review, Sprint 121-130 scope definition, runtime readiness continuation, permission audit writer boundaries, dashboard control center boundaries, ORION dry handshake boundaries, safe local action allowlist boundaries, runtime activation blocker tracking, and future checkpoint 130 boundaries without approving runtime, opening release gates, starting dashboard runtime, enabling audit writer runtime, performing ORION handshakes, or enabling runtime execution.",
                },
]


    def capability_summary(self) -> dict[str, Any]:
        catalog = self.capability_catalog()
        state_counts: dict[str, int] = {}
        risk_counts: dict[str, int] = {}
        permission_counts: dict[str, int] = {}

        for item in catalog:
            state_counts[item["state"]] = state_counts.get(item["state"], 0) + 1
            risk_counts[item["risk_level"]] = risk_counts.get(item["risk_level"], 0) + 1
            permission = item["permission_required"]
            permission_counts[permission] = permission_counts.get(permission, 0) + 1

        return {
            "total_capabilities": len(catalog),
            "online_capabilities": state_counts.get("online", 0),
            "foundation_only_count": sum(1 for item in catalog if item["runtime_level"] == "foundation_only"),
            "planner_only_count": sum(1 for item in catalog if item["runtime_level"] == "planner_only"),
            "permission_gated_count": sum(1 for item in catalog if "permission_gated" in item["runtime_level"]),
            "review_only_count": sum(1 for item in catalog if item["runtime_level"] == "review_only"),
            "planned_future_count": state_counts.get("planned_future", 0),
            "disabled_runtime_count": state_counts.get("disabled_runtime", 0),
            "runtime_execution_features": 0,
            "state_counts": state_counts,
            "risk_counts": risk_counts,
            "permission_counts": permission_counts,
        }

    def capabilities_by_state(self, state: str) -> list[dict[str, Any]]:
        return [item for item in self.capability_catalog() if item["state"] == state]

    def capabilities_requiring_permission(self) -> list[dict[str, Any]]:
        return [
            item for item in self.capability_catalog()
            if item["permission_required"] not in {"none", "read_project"}
        ]

    def control_center_catalog(self) -> list[dict[str, Any]]:
        return [
            {
                "id": item["id"],
                "name": item["name"],
                "state": item["state"],
                "runtime_level": item["runtime_level"],
                "risk_level": item["risk_level"],
                "permission_required": item["permission_required"],
                "category": item["category"],
                "visible": item["control_center_visible"],
            }
            for item in self.capability_catalog()
            if item["control_center_visible"]
        ]

    def normalize_text(self, text: Any) -> str:
        return " ".join(str(text or "").strip().split())

    def base_plan(self, plan_type: str, target: str) -> dict[str, Any]:
        normalized_target = self.normalize_text(target) or "AURA capability registry"
        boundary = self.safety_boundary()
        return {
            "name": self.name,
            "version": self.version,
            "status": "planned",
            "plan_type": plan_type,
            "target": normalized_target,
            "principle": "know_capabilities_before_runtime_actions",
            "registry_plan_types": self.registry_plan_types(),
            "capability_summary": self.capability_summary(),
            "safe_current_capabilities": self.safe_current_capabilities(),
            "disabled_capabilities": self.disabled_capabilities(),
            **boundary,
        }

    def capability_catalog_plan(self, target: str) -> dict[str, Any]:
        plan = self.base_plan("capability_catalog_plan", target)
        plan["catalog_steps"] = [
            "List currently online, foundation-only, planner-only, permission-gated, review-only, planned, and disabled runtime capabilities.",
            "Assign risk level to each capability.",
            "Assign required permission category to each capability.",
            "Expose display-safe capability data for the future Control Center.",
        ]
        return plan

    def capability_state_review_plan(self, target: str) -> dict[str, Any]:
        plan = self.base_plan("capability_state_review_plan", target)
        plan["state_review_steps"] = [
            "Confirm online capabilities do not imply runtime execution.",
            "Keep foundation-only systems separate from runtime-ready systems.",
            "Keep planner-only systems separate from action execution.",
            "Keep disabled runtime capabilities visible as deferred and locked.",
        ]
        return plan

    def permission_requirement_review_plan(self, target: str) -> dict[str, Any]:
        plan = self.base_plan("permission_requirement_review_plan", target)
        plan["permission_review_steps"] = [
            "Map every risky capability to a permission category.",
            "Use user confirmation for future service, launcher, UI, and permission workflow actions.",
            "Keep microphone, camera, screen, file, command, download, internet, desktop, and git permissions explicit.",
            "Do not grant permission from the registry itself.",
        ]
        return plan

    def risk_level_review_plan(self, target: str) -> dict[str, Any]:
        plan = self.base_plan("risk_level_review_plan", target)
        plan["risk_review_steps"] = [
            "Mark display-only and planning features as low risk.",
            "Mark intent, UI, launcher, and monitoring foundations as medium risk.",
            "Mark microphone, camera, visual context, dependency/download, service, and permission workflow as high risk.",
            "Mark file write and command execution runtime as critical and deferred.",
        ]
        return plan

    def control_center_capability_view_plan(self, target: str) -> dict[str, Any]:
        plan = self.base_plan("control_center_capability_view_plan", target)
        plan["control_center_cards"] = [
            "Capability name",
            "Current state",
            "Runtime level",
            "Risk level",
            "Permission required",
            "Introduced version",
            "Category",
        ]
        plan["control_center_rule"] = "Control Center may display capability status, but must not enable capabilities without explicit permission workflow."
        return plan

    def capability_gap_review_plan(self, target: str) -> dict[str, Any]:
        plan = self.base_plan("capability_gap_review_plan", target)
        plan["gap_review_steps"] = [
            "Identify planned 83-90 operational control foundations.",
            "Keep controlled file write and command execution runtime deferred to 91-100.",
            "Keep voice and vision runtime adapters deferred until service, permission, launcher, and console foundations are stable.",
            "Use registry visibility to prevent confusing planned features with active runtime features.",
        ]
        return plan

    def capability_registry_migration_plan(self, target: str) -> dict[str, Any]:
        plan = self.base_plan("capability_registry_migration_plan", target)
        plan["migration_steps"] = [
            "Introduce capability registry as read-only metadata first.",
            "Expose registry through skill, plugin, CLI, shell, and system status.",
            "Use registry data in future launcher and Control Center views.",
            "Do not migrate permission decisions into this registry; keep permission workflow separate.",
        ]
        return plan

    def context(self) -> dict[str, Any]:
        boundary = self.safety_boundary()
        return {
            "name": self.name,
            "version": self.version,
            "status": self.status_name,
            "registry_plan_types": self.registry_plan_types(),
            "capability_states": self.capability_states(),
            "risk_levels": self.risk_levels(),
            "permission_categories": self.permission_categories(),
            "capability_summary": self.capability_summary(),
            "capability_catalog": self.capability_catalog(),
            "control_center_catalog": self.control_center_catalog(),
            "safe_current_capabilities": self.safe_current_capabilities(),
            "disabled_capabilities": self.disabled_capabilities(),
            **boundary,
        }

    def status(self) -> dict[str, Any]:
        boundary = self.safety_boundary()
        summary = self.capability_summary()
        return {
            "name": self.name,
            "version": self.version,
            "status": self.status_name,
            "registry_ready": True,
            "planner_ready": True,
            "control_center_data_ready": True,
            "capability_catalog_plan_ready": True,
            "capability_state_review_plan_ready": True,
            "permission_requirement_review_plan_ready": True,
            "risk_level_review_plan_ready": True,
            "control_center_capability_view_plan_ready": True,
            "capability_gap_review_plan_ready": True,
            "capability_registry_migration_plan_ready": True,
            "context_ready": True,
            "registry_plan_types": self.registry_plan_types(),
            "plan_type_count": len(self.registry_plan_types()),
            **summary,
            **boundary,
        }
