import importlib.util
import os
import platform
import shutil
from pathlib import Path
from typing import Any

from aura.permissions.permission_manager import PermissionManager


class VoiceRuntimePlanner:
    """
    Voice Runtime Planning for AURA.

    Current phase:
    - plan STT/TTS runtime candidates
    - check passive dependency availability
    - map permissions and confirmation requirements
    - never access microphone or speaker
    """

    name = "voice_runtime_planning"
    version = "0.1.0"

    def __init__(self, project_root: Path):
        self.project_root = project_root
        self.permission_manager = PermissionManager()

    def stt_candidates(self) -> list[dict[str, Any]]:
        return [
            {
                "name": "faster-whisper",
                "type": "speech_to_text",
                "status": "candidate",
                "local_first": True,
                "offline_capable": True,
                "description": "Local Whisper-based speech recognition using CPU or GPU.",
                "notes": "Good default candidate for local STT on ATLAS.",
            },
            {
                "name": "whisper.cpp",
                "type": "speech_to_text",
                "status": "candidate",
                "local_first": True,
                "offline_capable": True,
                "description": "Lightweight native Whisper runtime.",
                "notes": "Good for efficient local inference and small models.",
            },
            {
                "name": "vosk",
                "type": "speech_to_text",
                "status": "candidate",
                "local_first": True,
                "offline_capable": True,
                "description": "Offline lightweight speech recognition.",
                "notes": "Useful fallback for low-resource STT.",
            },
        ]

    def tts_candidates(self) -> list[dict[str, Any]]:
        return [
            {
                "name": "piper",
                "type": "text_to_speech",
                "status": "candidate",
                "local_first": True,
                "offline_capable": True,
                "description": "Fast local neural text-to-speech.",
                "notes": "Good default candidate for local TTS.",
            },
            {
                "name": "coqui-tts",
                "type": "text_to_speech",
                "status": "candidate",
                "local_first": True,
                "offline_capable": True,
                "description": "Neural local TTS framework.",
                "notes": "Flexible but heavier than Piper.",
            },
            {
                "name": "espeak-ng",
                "type": "text_to_speech",
                "status": "fallback",
                "local_first": True,
                "offline_capable": True,
                "description": "Lightweight classic TTS engine.",
                "notes": "Good fallback for simple voice output testing.",
            },
        ]

    def dependency_check(self) -> dict[str, Any]:
        python_packages = [
            {
                "name": "sounddevice",
                "purpose": "microphone input and speaker output bridge",
                "installed": importlib.util.find_spec("sounddevice") is not None,
            },
            {
                "name": "numpy",
                "purpose": "audio buffer processing",
                "installed": importlib.util.find_spec("numpy") is not None,
            },
            {
                "name": "faster_whisper",
                "purpose": "candidate local STT runtime",
                "installed": importlib.util.find_spec("faster_whisper") is not None,
            },
            {
                "name": "vosk",
                "purpose": "candidate offline STT runtime",
                "installed": importlib.util.find_spec("vosk") is not None,
            },
        ]

        executables = [
            {
                "name": "ffmpeg",
                "purpose": "audio conversion and media handling",
                "found": shutil.which("ffmpeg") is not None,
            },
            {
                "name": "piper",
                "purpose": "candidate local TTS runtime",
                "found": shutil.which("piper") is not None,
            },
            {
                "name": "espeak-ng",
                "purpose": "fallback local TTS runtime",
                "found": shutil.which("espeak-ng") is not None,
            },
            {
                "name": "espeak",
                "purpose": "fallback local TTS runtime",
                "found": shutil.which("espeak") is not None,
            },
        ]

        return {
            "python_packages": python_packages,
            "executables": executables,
            "environment": {
                "os": platform.system() or "unknown",
                "os_release": platform.release() or "unknown",
                "machine": platform.machine() or "unknown",
                "pulse_server": os.environ.get("PULSE_SERVER") or "",
                "pipewire_runtime": os.environ.get("PIPEWIRE_RUNTIME_DIR") or "",
                "xdg_runtime": os.environ.get("XDG_RUNTIME_DIR") or "",
            },
            "note": "This is a passive check only. No microphone or speaker was accessed.",
        }

    def permission_map(self) -> dict[str, Any]:
        microphone = self.permission_manager.check("microphone_listen")
        speaker = self.permission_manager.check("speaker_speak")

        return {
            "microphone_listen": microphone.to_dict(),
            "speaker_speak": speaker.to_dict(),
        }


    def activation_contract(self) -> dict[str, Any]:
        return {
            "sprint": 191,
            "name": "voice_runtime_activation_foundation",
            "activation_foundation_ready": True,
            "runtime_ready": False,
            "safe_idle_default": True,
            "push_to_talk_required": True,
            "explicit_listen_required": True,
            "always_listening_enabled": False,
            "hidden_capture_enabled": False,
            "background_wake_word_enabled": False,
            "silent_cloud_fallback_enabled": False,
            "direct_voice_to_action_enabled": False,
            "microphone_capture_active": False,
            "speaker_playback_active": False,
            "stt_runtime_active": False,
            "tts_runtime_active": False,
            "audio_file_write_active": False,
            "command_execution_active": False,
            "microphone_permission_action": "microphone_listen",
            "speaker_permission_action": "speaker_speak",
            "chat_session_reuse_required": True,
            "control_center_voice_controls_deferred": True,
            "next_sprint": 192,
            "next_boundary": "push_to_talk_and_explicit_listen_state",
            "guardrails": [
                "No always-listening mode.",
                "No hidden microphone capture.",
                "No background wake word.",
                "No direct voice-to-action execution.",
                "No silent cloud STT or TTS fallback.",
                "Reuse the stable chat/session interaction path.",
            ],
        }


    def listen_state_contract(self) -> dict[str, Any]:
        allowed_states = [
            "idle",
            "listen_requested",
            "permission_required",
            "listen_ready",
            "listening_explicit",
            "listen_stopping",
            "listen_stopped",
            "listen_denied",
            "listen_error",
        ]

        transitions = {
            "idle": ["listen_requested"],
            "listen_requested": ["permission_required", "listen_ready", "listen_denied"],
            "permission_required": ["listen_ready", "listen_denied"],
            "listen_ready": ["listening_explicit", "listen_stopped"],
            "listening_explicit": ["listen_stopping", "listen_error"],
            "listen_stopping": ["listen_stopped", "listen_error"],
            "listen_stopped": ["idle"],
            "listen_denied": ["idle"],
            "listen_error": ["idle"],
        }

        return {
            "sprint": 192,
            "name": "push_to_talk_explicit_listen_state",
            "listen_state_foundation_ready": True,
            "default_state": "idle",
            "current_state": "idle",
            "allowed_states": allowed_states,
            "transition_map": transitions,
            "push_to_talk_required": True,
            "explicit_listen_required": True,
            "explicit_stop_required": True,
            "permission_required_before_listening": True,
            "microphone_permission_action": "microphone_listen",
            "microphone_capture_active": False,
            "audio_buffer_active": False,
            "stt_runtime_active": False,
            "listen_loop_active": False,
            "background_listener_active": False,
            "wake_word_active": False,
            "always_listening_enabled": False,
            "hidden_capture_enabled": False,
            "silent_cloud_fallback_enabled": False,
            "direct_voice_to_action_enabled": False,
            "state_persistence_runtime": False,
            "state_mutation_runtime": False,
            "audio_device_access": False,
            "command_execution_active": False,
            "next_sprint": 193,
            "next_boundary": "local_microphone_capture_boundary",
            "guardrails": [
                "Default listen state is idle.",
                "Listening can only begin from explicit push-to-talk request.",
                "Microphone permission is required before any future live listening.",
                "No microphone capture is performed in Sprint 192.",
                "No audio buffer, STT runtime, wake word, or background listener is active.",
                "No direct voice-to-action execution is allowed.",
            ],
        }


    def microphone_capture_boundary_contract(self) -> dict[str, Any]:
        dependency_check = self.dependency_check()
        sounddevice_available = any(
            package["name"] == "sounddevice" and package["installed"]
            for package in dependency_check["python_packages"]
        )

        return {
            "sprint": 193,
            "name": "local_microphone_capture_boundary",
            "microphone_boundary_ready": True,
            "microphone_capture_runtime_ready": False,
            "microphone_capture_active": False,
            "microphone_permission_action": "microphone_listen",
            "permission_required_before_capture": True,
            "explicit_listen_state_required_before_capture": True,
            "required_listen_state_before_capture": "listening_explicit",
            "push_to_talk_required_before_capture": True,
            "audio_device_access": False,
            "audio_device_discovery_active": False,
            "device_enumeration_performed": False,
            "sounddevice_available": sounddevice_available,
            "sounddevice_runtime_imported": False,
            "recording_enabled": False,
            "recording_active": False,
            "audio_buffer_active": False,
            "audio_file_write_active": False,
            "audio_persistence_enabled": False,
            "audio_transmission_enabled": False,
            "stt_runtime_active": False,
            "transcription_active": False,
            "listen_loop_active": False,
            "background_listener_active": False,
            "wake_word_active": False,
            "always_listening_enabled": False,
            "hidden_capture_enabled": False,
            "silent_cloud_fallback_enabled": False,
            "direct_voice_to_action_enabled": False,
            "command_execution_active": False,
            "speaker_playback_active": False,
            "capture_scope": "boundary_contract_only",
            "retention_policy": "no_audio_retention_in_sprint_193",
            "next_sprint": 194,
            "next_boundary": "speech_to_text_adapter_runtime",
            "guardrails": [
                "No microphone capture is performed in Sprint 193.",
                "No audio device discovery is performed in Sprint 193.",
                "No audio buffer, recording, or audio file write is active.",
                "No STT or transcription runtime is active.",
                "Future capture requires explicit listen state and microphone permission.",
                "No always-listening, hidden capture, wake word, or background listener is active.",
            ],
        }


    def speech_to_text_adapter_runtime_contract(self) -> dict[str, Any]:
        dependency_check = self.dependency_check()
        python_packages = {
            package["name"]: package["installed"]
            for package in dependency_check["python_packages"]
        }
        executables = {
            executable["name"]: executable["found"]
            for executable in dependency_check["executables"]
        }
        candidates = self.stt_candidates()

        return {
            "sprint": 194,
            "name": "speech_to_text_adapter_runtime",
            "stt_adapter_contract_ready": True,
            "stt_adapter_runtime_ready": False,
            "default_adapter": "faster-whisper",
            "candidate_adapters": [candidate["name"] for candidate in candidates],
            "candidate_adapter_count": len(candidates),
            "local_first_required": True,
            "offline_first_required": True,
            "audio_file_input_boundary_ready": True,
            "provided_audio_file_required_for_future_dry_run": True,
            "audio_file_transcription_runtime_ready": False,
            "audio_file_read_active": False,
            "audio_file_write_active": False,
            "microphone_capture_required_for_adapter_contract": False,
            "live_microphone_transcription_active": False,
            "microphone_capture_active": False,
            "audio_device_access": False,
            "audio_device_discovery_active": False,
            "recording_active": False,
            "audio_buffer_active": False,
            "audio_persistence_enabled": False,
            "audio_transmission_enabled": False,
            "stt_runtime_active": False,
            "transcription_active": False,
            "transcript_persistence_enabled": False,
            "transcript_to_chat_handoff_enabled": False,
            "transcript_to_action_enabled": False,
            "command_execution_active": False,
            "model_download_required": False,
            "model_download_performed": False,
            "dependency_install_performed": False,
            "cloud_stt_fallback_enabled": False,
            "silent_cloud_fallback_enabled": False,
            "remote_provider_enabled": False,
            "permission_required_before_transcription": True,
            "microphone_permission_action": "microphone_listen",
            "faster_whisper_available": python_packages.get("faster_whisper", False),
            "vosk_available": python_packages.get("vosk", False),
            "ffmpeg_available": executables.get("ffmpeg", False),
            "runtime_scope": "adapter_contract_only",
            "next_sprint": 195,
            "next_boundary": "voice_intent_and_chat_integration",
            "guardrails": [
                "No STT runtime is executed in Sprint 194.",
                "No audio file is read or written in Sprint 194.",
                "No live microphone transcription is active.",
                "No model download or dependency installation is performed.",
                "No cloud STT or silent fallback is enabled.",
                "Transcripts cannot trigger chat handoff or actions in Sprint 194.",
            ],
        }


    def voice_intent_chat_integration_contract(self) -> dict[str, Any]:
        return {
            "sprint": 195,
            "name": "voice_intent_and_chat_integration",
            "voice_intent_chat_contract_ready": True,
            "voice_intent_runtime_ready": False,
            "voice_intent_layer_contract_ready": True,
            "transcript_source": "contract_only",
            "transcript_input_boundary_ready": True,
            "provided_transcript_required_for_future_dry_run": True,
            "dummy_transcript_allowed_for_contract": True,
            "live_transcript_input_active": False,
            "transcript_normalization_contract_ready": True,
            "transcript_normalization_runtime_active": False,
            "intent_classification_contract_ready": True,
            "intent_classification_runtime_active": False,
            "intent_confidence_runtime_active": False,
            "clarification_gate_contract_ready": True,
            "action_intent_gate_contract_ready": True,
            "voice_response_plan_contract_ready": True,
            "transcript_to_chat_handoff_contract_ready": True,
            "transcript_to_chat_handoff_active": False,
            "chat_session_reuse_required": True,
            "chat_session_write_active": False,
            "chat_model_request_active": False,
            "chat_response_generation_active": False,
            "permission_required_before_chat_handoff": True,
            "human_confirmation_required_for_action_intent": True,
            "transcript_persistence_enabled": False,
            "memory_write_active": False,
            "direct_voice_to_action_enabled": False,
            "tool_execution_active": False,
            "command_execution_active": False,
            "file_mutation_active": False,
            "desktop_action_active": False,
            "network_action_active": False,
            "git_action_active": False,
            "stt_runtime_active": False,
            "transcription_active": False,
            "live_microphone_transcription_active": False,
            "tts_runtime_active": False,
            "speaker_playback_active": False,
            "cloud_stt_fallback_enabled": False,
            "silent_cloud_fallback_enabled": False,
            "runtime_scope": "voice_intent_chat_contract_only",
            "next_sprint": 196,
            "next_boundary": "text_to_speech_adapter_runtime",
            "guardrails": [
                "No live transcript input is processed in Sprint 195.",
                "No transcript is handed to chat automatically in Sprint 195.",
                "No chat session write or model request is performed by the voice layer.",
                "No direct voice-to-action execution is allowed.",
                "No tools, commands, files, desktop, network, git, or memory writes are executed.",
                "Action-like voice intent requires future explicit human confirmation.",
            ],
        }


    def text_to_speech_adapter_runtime_contract(self) -> dict[str, Any]:
        candidates = self.tts_candidates()
        return {
            "sprint": 196,
            "name": "text_to_speech_adapter_runtime",
            "tts_adapter_contract_ready": True,
            "tts_adapter_runtime_ready": False,
            "default_adapter": "piper",
            "candidate_adapters": [candidate["name"] for candidate in candidates],
            "candidate_adapter_count": len(candidates),
            "local_first_required": True,
            "offline_first_required": True,
            "voice_response_input_boundary_ready": True,
            "provided_text_required_for_future_dry_run": True,
            "dummy_text_allowed_for_contract": True,
            "tts_text_normalization_contract_ready": True,
            "tts_synthesis_runtime_ready": False,
            "tts_synthesis_runtime_active": False,
            "audio_output_file_boundary_ready": True,
            "audio_output_file_write_active": False,
            "audio_output_file_read_active": False,
            "audio_file_persistence_enabled": False,
            "speaker_playback_permission_required": True,
            "speaker_permission_action": "speaker_speak",
            "speaker_playback_runtime_ready": False,
            "speaker_playback_active": False,
            "audio_playback_device_access": False,
            "audio_playback_device_discovery_active": False,
            "playback_enabled": False,
            "automatic_speak_after_chat_enabled": False,
            "voice_response_playback_active": False,
            "chat_response_to_tts_handoff_contract_ready": True,
            "chat_response_to_tts_handoff_active": False,
            "model_download_required": False,
            "model_download_performed": False,
            "dependency_install_performed": False,
            "cloud_tts_fallback_enabled": False,
            "silent_cloud_fallback_enabled": False,
            "remote_tts_provider_enabled": False,
            "stt_runtime_active": False,
            "transcription_active": False,
            "microphone_capture_active": False,
            "audio_device_access": False,
            "audio_buffer_active": False,
            "memory_write_active": False,
            "direct_voice_to_action_enabled": False,
            "tool_execution_active": False,
            "command_execution_active": False,
            "file_mutation_active": False,
            "desktop_action_active": False,
            "network_action_active": False,
            "git_action_active": False,
            "runtime_scope": "text_to_speech_adapter_contract_only",
            "next_sprint": 197,
            "next_boundary": "voice_permission_and_audit_runtime",
            "guardrails": [
                "No TTS synthesis runtime is executed in Sprint 196.",
                "No audio output file is written in Sprint 196.",
                "No speaker playback or playback device access is active.",
                "No automatic speak-after-chat handoff is enabled.",
                "No cloud TTS or silent fallback is enabled.",
                "No tools, commands, files, desktop, network, git, or memory writes are executed.",
            ],
        }


    def voice_permission_audit_runtime_contract(self) -> dict[str, Any]:
        microphone_permission = self.permission_manager.check("microphone_listen")
        speaker_permission = self.permission_manager.check("speaker_speak")
        audit_event_types = [
            "voice.permission.boundary_checked",
            "voice.microphone.permission_required",
            "voice.speaker.permission_required",
            "voice.transcript_handoff.permission_required",
            "voice.action_intent.confirmation_required",
            "voice.audit.write_blocked",
        ]
        return {
            "sprint": 197,
            "name": "voice_permission_and_audit_runtime",
            "voice_permission_audit_contract_ready": True,
            "voice_permission_audit_runtime_ready": False,
            "permission_boundary_ready": True,
            "microphone_permission_action": "microphone_listen",
            "speaker_permission_action": "speaker_speak",
            "microphone_permission_required": True,
            "speaker_permission_required": True,
            "microphone_permission_allowed": microphone_permission.allowed,
            "speaker_permission_allowed": speaker_permission.allowed,
            "microphone_permission_requires_confirmation": microphone_permission.requires_confirmation,
            "speaker_permission_requires_confirmation": speaker_permission.requires_confirmation,
            "microphone_permission": microphone_permission.to_dict(),
            "speaker_permission": speaker_permission.to_dict(),
            "transcript_chat_handoff_permission_required": True,
            "chat_response_tts_permission_required": True,
            "voice_action_permission_required": True,
            "permission_before_microphone_capture": True,
            "permission_before_stt": True,
            "permission_before_tts": True,
            "permission_before_speaker_playback": True,
            "permission_before_chat_handoff": True,
            "human_confirmation_required_for_voice_action_intent": True,
            "audit_event_contract_ready": True,
            "audit_event_schema_ready": True,
            "audit_event_types": audit_event_types,
            "audit_event_type_count": len(audit_event_types),
            "audit_event_redaction_boundary_ready": True,
            "audit_event_local_only_required": True,
            "audit_event_append_only_boundary_ready": True,
            "audit_write_runtime_ready": False,
            "audit_write_runtime_active": False,
            "audit_event_persistence_enabled": False,
            "audit_log_append_active": False,
            "audit_storage_write_active": False,
            "audit_dashboard_event_emit_active": False,
            "audit_redaction_runtime_active": False,
            "audit_permission_link_runtime_active": False,
            "review_queue_contract_ready": True,
            "review_queue_runtime_active": False,
            "recovery_visibility_contract_ready": True,
            "recovery_action_runtime_active": False,
            "permission_decision_runtime_active": False,
            "permission_grant_runtime_active": False,
            "permission_revoke_runtime_active": False,
            "permission_persistence_active": False,
            "permission_mutation_active": False,
            "microphone_capture_active": False,
            "stt_runtime_active": False,
            "transcription_active": False,
            "live_microphone_transcription_active": False,
            "tts_runtime_active": False,
            "tts_synthesis_runtime_active": False,
            "speaker_playback_active": False,
            "audio_device_access": False,
            "playback_device_access": False,
            "audio_buffer_active": False,
            "transcript_to_chat_handoff_active": False,
            "chat_response_to_tts_handoff_active": False,
            "memory_write_active": False,
            "direct_voice_to_action_enabled": False,
            "tool_execution_active": False,
            "command_execution_active": False,
            "file_mutation_active": False,
            "desktop_action_active": False,
            "network_action_active": False,
            "git_action_active": False,
            "cloud_stt_fallback_enabled": False,
            "cloud_tts_fallback_enabled": False,
            "silent_cloud_fallback_enabled": False,
            "runtime_scope": "voice_permission_audit_contract_only",
            "next_sprint": 198,
            "next_boundary": "control_center_voice_controls",
            "guardrails": [
                "No permission grant, revoke, mutation, or persistence runtime is enabled.",
                "No audit event writer, log append, storage write, or dashboard emit runtime is enabled.",
                "Microphone and speaker actions reuse explicit confirmation permission boundaries.",
                "No microphone capture, STT, TTS, speaker playback, or voice action execution is enabled.",
                "No tools, commands, files, desktop, network, git, or memory writes are executed.",
            ],
        }

    def status(self) -> dict[str, Any]:
        stt_candidates = self.stt_candidates()
        tts_candidates = self.tts_candidates()
        activation = self.activation_contract()
        listen_state = self.listen_state_contract()
        microphone_boundary = self.microphone_capture_boundary_contract()
        stt_adapter = self.speech_to_text_adapter_runtime_contract()
        voice_intent_chat = self.voice_intent_chat_integration_contract()
        tts_adapter = self.text_to_speech_adapter_runtime_contract()
        voice_permission_audit = self.voice_permission_audit_runtime_contract()

        return {
            "name": self.name,
            "version": self.version,
            "status": "planning",
            "planning_ready": True,
            "activation_foundation_ready": activation["activation_foundation_ready"],
            "listen_state_foundation_ready": listen_state["listen_state_foundation_ready"],
            "default_listen_state": listen_state["default_state"],
            "current_listen_state": listen_state["current_state"],
            "allowed_listen_states": len(listen_state["allowed_states"]),
            "microphone_boundary_ready": microphone_boundary["microphone_boundary_ready"],
            "microphone_capture_runtime_ready": microphone_boundary["microphone_capture_runtime_ready"],
            "microphone_capture_active": microphone_boundary["microphone_capture_active"],
            "audio_device_access": microphone_boundary["audio_device_access"],
            "audio_device_discovery_active": microphone_boundary["audio_device_discovery_active"],
            "recording_active": microphone_boundary["recording_active"],
            "audio_buffer_active": microphone_boundary["audio_buffer_active"],
            "stt_adapter_contract_ready": stt_adapter["stt_adapter_contract_ready"],
            "stt_adapter_runtime_ready": stt_adapter["stt_adapter_runtime_ready"],
            "stt_default_adapter": stt_adapter["default_adapter"],
            "stt_adapter_candidates": stt_adapter["candidate_adapter_count"],
            "audio_file_transcription_runtime_ready": stt_adapter["audio_file_transcription_runtime_ready"],
            "live_microphone_transcription_active": stt_adapter["live_microphone_transcription_active"],
            "transcription_active": stt_adapter["transcription_active"],
            "cloud_stt_fallback_enabled": stt_adapter["cloud_stt_fallback_enabled"],
            "transcript_to_action_enabled": stt_adapter["transcript_to_action_enabled"],
            "voice_intent_chat_contract_ready": voice_intent_chat["voice_intent_chat_contract_ready"],
            "voice_intent_runtime_ready": voice_intent_chat["voice_intent_runtime_ready"],
            "transcript_source": voice_intent_chat["transcript_source"],
            "transcript_to_chat_handoff_ready": voice_intent_chat["transcript_to_chat_handoff_contract_ready"],
            "transcript_to_chat_handoff_active": voice_intent_chat["transcript_to_chat_handoff_active"],
            "intent_classification_runtime_active": voice_intent_chat["intent_classification_runtime_active"],
            "chat_session_write_active": voice_intent_chat["chat_session_write_active"],
            "voice_intent_direct_voice_to_action_enabled": voice_intent_chat["direct_voice_to_action_enabled"],
            "voice_intent_command_execution_active": voice_intent_chat["command_execution_active"],
            "runtime_ready": False,
            "safe_idle_default": activation["safe_idle_default"],
            "push_to_talk_required": activation["push_to_talk_required"],
            "always_listening_enabled": activation["always_listening_enabled"],
            "hidden_capture_enabled": activation["hidden_capture_enabled"],
            "background_wake_word_enabled": activation["background_wake_word_enabled"],
            "silent_cloud_fallback_enabled": activation["silent_cloud_fallback_enabled"],
            "direct_voice_to_action_enabled": activation["direct_voice_to_action_enabled"],
            "chat_session_reuse_required": activation["chat_session_reuse_required"],
            "microphone_access": False,
            "speaker_output": False,
            "stt_runtime_ready": False,
            "tts_runtime_ready": False,
            "tts_adapter_contract_ready": tts_adapter["tts_adapter_contract_ready"],
            "tts_adapter_runtime_ready": tts_adapter["tts_adapter_runtime_ready"],
            "tts_default_adapter": tts_adapter["default_adapter"],
            "tts_adapter_candidates": tts_adapter["candidate_adapter_count"],
            "voice_response_input_boundary_ready": tts_adapter["voice_response_input_boundary_ready"],
            "tts_synthesis_runtime_active": tts_adapter["tts_synthesis_runtime_active"],
            "speaker_playback_active": tts_adapter["speaker_playback_active"],
            "audio_output_file_write_active": tts_adapter["audio_output_file_write_active"],
            "automatic_speak_after_chat_enabled": tts_adapter["automatic_speak_after_chat_enabled"],
            "cloud_tts_fallback_enabled": tts_adapter["cloud_tts_fallback_enabled"],
            "voice_permission_audit_contract_ready": voice_permission_audit["voice_permission_audit_contract_ready"],
            "voice_permission_audit_runtime_ready": voice_permission_audit["voice_permission_audit_runtime_ready"],
            "voice_permission_boundary_ready": voice_permission_audit["permission_boundary_ready"],
            "voice_microphone_permission_action": voice_permission_audit["microphone_permission_action"],
            "voice_speaker_permission_action": voice_permission_audit["speaker_permission_action"],
            "voice_microphone_permission_requires_confirmation": voice_permission_audit["microphone_permission_requires_confirmation"],
            "voice_speaker_permission_requires_confirmation": voice_permission_audit["speaker_permission_requires_confirmation"],
            "voice_audit_event_contract_ready": voice_permission_audit["audit_event_contract_ready"],
            "voice_audit_write_runtime_active": voice_permission_audit["audit_write_runtime_active"],
            "voice_permission_decision_runtime_active": voice_permission_audit["permission_decision_runtime_active"],
            "voice_permission_grant_runtime_active": voice_permission_audit["permission_grant_runtime_active"],
            "voice_permission_mutation_active": voice_permission_audit["permission_mutation_active"],
            "stt_candidates": len(stt_candidates),
            "tts_candidates": len(tts_candidates),
            "candidate_count": len(stt_candidates) + len(tts_candidates),
            "permissions": self.permission_map(),
            "activation_contract": activation,
            "listen_state_contract": listen_state,
            "microphone_capture_boundary_contract": microphone_boundary,
            "speech_to_text_adapter_runtime_contract": stt_adapter,
            "voice_intent_chat_integration_contract": voice_intent_chat,
            "text_to_speech_adapter_runtime_contract": tts_adapter,
            "voice_permission_audit_runtime_contract": voice_permission_audit,
            "note": "Voice permission and audit contract is ready, but permission grant/mutation, audit writes, microphone capture, STT, TTS, speaker playback, and voice actions are not enabled yet.",
        }

    def plan(self) -> dict[str, Any]:
        return {
            "recommended_path": {
                "stt": "faster-whisper",
                "tts": "piper",
                "fallback_tts": "espeak-ng",
                "audio_io": "sounddevice",
                "description": "Use local offline STT/TTS first, then connect microphone/speaker only after explicit confirmation.",
            },
            "phases": [
                {
                    "phase": 1,
                    "name": "Runtime package planning",
                    "status": "ready_to_plan",
                    "description": "Choose STT/TTS providers and document dependency requirements.",
                },
                {
                    "phase": 2,
                    "name": "Passive dependency check",
                    "status": "ready",
                    "description": "Check installed packages and executables without accessing audio devices.",
                },
                {
                    "phase": 3,
                    "name": "Audio device discovery",
                    "status": "future",
                    "description": "List microphone/speaker devices only after user approval.",
                },
                {
                    "phase": 4,
                    "name": "STT dry run",
                    "status": "future",
                    "description": "Test speech-to-text with a provided audio file before live microphone input.",
                },
                {
                    "phase": 5,
                    "name": "TTS dry run",
                    "status": "future",
                    "description": "Generate TTS output to a file before speaker playback.",
                },
                {
                    "phase": 6,
                    "name": "Voice loop alpha",
                    "status": "future",
                    "description": "Connect listen-think-speak loop with confirmation and runtime safety flags.",
                },
            ],
            "stt_candidates": self.stt_candidates(),
            "tts_candidates": self.tts_candidates(),
            "permissions": self.permission_map(),
            "safety_rules": [
                "Do not access microphone without explicit user confirmation.",
                "Do not play speaker output without explicit user confirmation.",
                "Prefer dry-run audio files before live audio devices.",
                "Keep all voice runtime actions local-first when possible.",
                "Keep runtime flags false until real STT/TTS is connected and tested.",
            ],
        }

    def check(self) -> dict[str, Any]:
        dependencies = self.dependency_check()
        activation = self.activation_contract()
        listen_state = self.listen_state_contract()
        microphone_boundary = self.microphone_capture_boundary_contract()
        stt_adapter = self.speech_to_text_adapter_runtime_contract()
        voice_intent_chat = self.voice_intent_chat_integration_contract()
        tts_adapter = self.text_to_speech_adapter_runtime_contract()
        voice_permission_audit = self.voice_permission_audit_runtime_contract()

        installed_python = sum(
            1
            for package in dependencies["python_packages"]
            if package["installed"]
        )

        found_executables = sum(
            1
            for executable in dependencies["executables"]
            if executable["found"]
        )

        assertions = {
            "activation_foundation_ready": activation["activation_foundation_ready"] is True,
            "runtime_not_enabled": activation["runtime_ready"] is False,
            "safe_idle_default": activation["safe_idle_default"] is True,
            "push_to_talk_required": activation["push_to_talk_required"] is True,
            "explicit_listen_required": activation["explicit_listen_required"] is True,
            "always_listening_disabled": activation["always_listening_enabled"] is False,
            "hidden_capture_disabled": activation["hidden_capture_enabled"] is False,
            "background_wake_word_disabled": activation["background_wake_word_enabled"] is False,
            "silent_cloud_fallback_disabled": activation["silent_cloud_fallback_enabled"] is False,
            "direct_voice_to_action_disabled": activation["direct_voice_to_action_enabled"] is False,
            "microphone_capture_inactive": activation["microphone_capture_active"] is False,
            "speaker_playback_inactive": activation["speaker_playback_active"] is False,
            "stt_runtime_inactive": activation["stt_runtime_active"] is False,
            "tts_runtime_inactive": activation["tts_runtime_active"] is False,
            "audio_file_write_inactive": activation["audio_file_write_active"] is False,
            "command_execution_inactive": activation["command_execution_active"] is False,
            "microphone_permission_reuses_existing_action": activation["microphone_permission_action"] == "microphone_listen",
            "speaker_permission_reuses_existing_action": activation["speaker_permission_action"] == "speaker_speak",
            "chat_session_reuse_required": activation["chat_session_reuse_required"] is True,
            "listen_state_foundation_ready": listen_state["listen_state_foundation_ready"] is True,
            "default_listen_state_idle": listen_state["default_state"] == "idle",
            "current_listen_state_idle": listen_state["current_state"] == "idle",
            "push_to_talk_still_required_for_listen": listen_state["push_to_talk_required"] is True,
            "explicit_listen_still_required": listen_state["explicit_listen_required"] is True,
            "explicit_stop_required": listen_state["explicit_stop_required"] is True,
            "microphone_permission_required_before_listening": listen_state["permission_required_before_listening"] is True,
            "listen_microphone_permission_reuses_existing_action": listen_state["microphone_permission_action"] == "microphone_listen",
            "listen_microphone_capture_inactive": listen_state["microphone_capture_active"] is False,
            "listen_audio_buffer_inactive": listen_state["audio_buffer_active"] is False,
            "listen_stt_runtime_inactive": listen_state["stt_runtime_active"] is False,
            "listen_loop_inactive": listen_state["listen_loop_active"] is False,
            "background_listener_inactive": listen_state["background_listener_active"] is False,
            "wake_word_inactive": listen_state["wake_word_active"] is False,
            "listen_state_persistence_disabled": listen_state["state_persistence_runtime"] is False,
            "listen_state_mutation_runtime_disabled": listen_state["state_mutation_runtime"] is False,
            "audio_device_access_disabled": listen_state["audio_device_access"] is False,
            "microphone_boundary_ready": microphone_boundary["microphone_boundary_ready"] is True,
            "microphone_capture_runtime_not_ready": microphone_boundary["microphone_capture_runtime_ready"] is False,
            "permission_required_before_capture": microphone_boundary["permission_required_before_capture"] is True,
            "explicit_listen_state_required_before_capture": microphone_boundary["explicit_listen_state_required_before_capture"] is True,
            "required_capture_state_is_listening_explicit": microphone_boundary["required_listen_state_before_capture"] == "listening_explicit",
            "push_to_talk_required_before_capture": microphone_boundary["push_to_talk_required_before_capture"] is True,
            "capture_microphone_permission_reuses_existing_action": microphone_boundary["microphone_permission_action"] == "microphone_listen",
            "capture_audio_device_access_disabled": microphone_boundary["audio_device_access"] is False,
            "capture_audio_device_discovery_inactive": microphone_boundary["audio_device_discovery_active"] is False,
            "device_enumeration_not_performed": microphone_boundary["device_enumeration_performed"] is False,
            "microphone_capture_inactive_for_boundary": microphone_boundary["microphone_capture_active"] is False,
            "sounddevice_runtime_not_imported": microphone_boundary["sounddevice_runtime_imported"] is False,
            "recording_disabled_for_boundary": microphone_boundary["recording_enabled"] is False,
            "recording_inactive_for_boundary": microphone_boundary["recording_active"] is False,
            "audio_buffer_inactive_for_capture": microphone_boundary["audio_buffer_active"] is False,
            "audio_file_write_inactive_for_capture": microphone_boundary["audio_file_write_active"] is False,
            "audio_persistence_disabled_for_capture": microphone_boundary["audio_persistence_enabled"] is False,
            "audio_transmission_disabled_for_capture": microphone_boundary["audio_transmission_enabled"] is False,
            "stt_runtime_inactive_for_capture": microphone_boundary["stt_runtime_active"] is False,
            "transcription_inactive_for_capture": microphone_boundary["transcription_active"] is False,
            "listen_loop_inactive_for_capture": microphone_boundary["listen_loop_active"] is False,
            "background_listener_inactive_for_capture": microphone_boundary["background_listener_active"] is False,
            "wake_word_inactive_for_capture": microphone_boundary["wake_word_active"] is False,
            "always_listening_disabled_for_capture": microphone_boundary["always_listening_enabled"] is False,
            "hidden_capture_disabled_for_capture": microphone_boundary["hidden_capture_enabled"] is False,
            "silent_cloud_fallback_disabled_for_capture": microphone_boundary["silent_cloud_fallback_enabled"] is False,
            "direct_voice_to_action_disabled_for_capture": microphone_boundary["direct_voice_to_action_enabled"] is False,
            "command_execution_inactive_for_capture": microphone_boundary["command_execution_active"] is False,
            "stt_adapter_contract_ready": stt_adapter["stt_adapter_contract_ready"] is True,
            "stt_adapter_runtime_not_ready": stt_adapter["stt_adapter_runtime_ready"] is False,
            "stt_default_adapter_is_faster_whisper": stt_adapter["default_adapter"] == "faster-whisper",
            "stt_candidate_adapter_count_matches": stt_adapter["candidate_adapter_count"] == len(self.stt_candidates()),
            "stt_local_first_required": stt_adapter["local_first_required"] is True,
            "stt_offline_first_required": stt_adapter["offline_first_required"] is True,
            "audio_file_input_boundary_ready": stt_adapter["audio_file_input_boundary_ready"] is True,
            "future_audio_file_required_for_stt_dry_run": stt_adapter["provided_audio_file_required_for_future_dry_run"] is True,
            "audio_file_transcription_runtime_not_ready": stt_adapter["audio_file_transcription_runtime_ready"] is False,
            "stt_audio_file_read_inactive": stt_adapter["audio_file_read_active"] is False,
            "stt_audio_file_write_inactive": stt_adapter["audio_file_write_active"] is False,
            "microphone_capture_not_required_for_stt_adapter_contract": stt_adapter["microphone_capture_required_for_adapter_contract"] is False,
            "live_microphone_transcription_inactive": stt_adapter["live_microphone_transcription_active"] is False,
            "stt_microphone_capture_inactive": stt_adapter["microphone_capture_active"] is False,
            "stt_audio_device_access_disabled": stt_adapter["audio_device_access"] is False,
            "stt_audio_device_discovery_inactive": stt_adapter["audio_device_discovery_active"] is False,
            "stt_recording_inactive": stt_adapter["recording_active"] is False,
            "stt_audio_buffer_inactive": stt_adapter["audio_buffer_active"] is False,
            "stt_audio_persistence_disabled": stt_adapter["audio_persistence_enabled"] is False,
            "stt_audio_transmission_disabled": stt_adapter["audio_transmission_enabled"] is False,
            "stt_runtime_inactive_for_adapter": stt_adapter["stt_runtime_active"] is False,
            "transcription_inactive_for_stt_adapter": stt_adapter["transcription_active"] is False,
            "transcript_persistence_disabled": stt_adapter["transcript_persistence_enabled"] is False,
            "transcript_to_chat_handoff_disabled": stt_adapter["transcript_to_chat_handoff_enabled"] is False,
            "transcript_to_action_disabled": stt_adapter["transcript_to_action_enabled"] is False,
            "stt_command_execution_inactive": stt_adapter["command_execution_active"] is False,
            "stt_model_download_not_required": stt_adapter["model_download_required"] is False,
            "stt_model_download_not_performed": stt_adapter["model_download_performed"] is False,
            "stt_dependency_install_not_performed": stt_adapter["dependency_install_performed"] is False,
            "cloud_stt_fallback_disabled": stt_adapter["cloud_stt_fallback_enabled"] is False,
            "silent_cloud_stt_fallback_disabled": stt_adapter["silent_cloud_fallback_enabled"] is False,
            "remote_stt_provider_disabled": stt_adapter["remote_provider_enabled"] is False,
            "permission_required_before_transcription": stt_adapter["permission_required_before_transcription"] is True,
            "stt_microphone_permission_reuses_existing_action": stt_adapter["microphone_permission_action"] == "microphone_listen",
            "voice_intent_chat_contract_ready": voice_intent_chat["voice_intent_chat_contract_ready"] is True,
            "voice_intent_runtime_not_ready": voice_intent_chat["voice_intent_runtime_ready"] is False,
            "voice_intent_layer_contract_ready": voice_intent_chat["voice_intent_layer_contract_ready"] is True,
            "voice_transcript_source_contract_only": voice_intent_chat["transcript_source"] == "contract_only",
            "voice_transcript_input_boundary_ready": voice_intent_chat["transcript_input_boundary_ready"] is True,
            "future_provided_transcript_required": voice_intent_chat["provided_transcript_required_for_future_dry_run"] is True,
            "dummy_transcript_allowed_for_contract": voice_intent_chat["dummy_transcript_allowed_for_contract"] is True,
            "live_transcript_input_inactive": voice_intent_chat["live_transcript_input_active"] is False,
            "transcript_normalization_contract_ready": voice_intent_chat["transcript_normalization_contract_ready"] is True,
            "transcript_normalization_runtime_inactive": voice_intent_chat["transcript_normalization_runtime_active"] is False,
            "intent_classification_contract_ready": voice_intent_chat["intent_classification_contract_ready"] is True,
            "intent_classification_runtime_inactive": voice_intent_chat["intent_classification_runtime_active"] is False,
            "intent_confidence_runtime_inactive": voice_intent_chat["intent_confidence_runtime_active"] is False,
            "clarification_gate_contract_ready": voice_intent_chat["clarification_gate_contract_ready"] is True,
            "action_intent_gate_contract_ready": voice_intent_chat["action_intent_gate_contract_ready"] is True,
            "voice_response_plan_contract_ready": voice_intent_chat["voice_response_plan_contract_ready"] is True,
            "transcript_to_chat_handoff_contract_ready": voice_intent_chat["transcript_to_chat_handoff_contract_ready"] is True,
            "transcript_to_chat_handoff_inactive": voice_intent_chat["transcript_to_chat_handoff_active"] is False,
            "voice_chat_session_reuse_required": voice_intent_chat["chat_session_reuse_required"] is True,
            "voice_chat_session_write_inactive": voice_intent_chat["chat_session_write_active"] is False,
            "voice_chat_model_request_inactive": voice_intent_chat["chat_model_request_active"] is False,
            "voice_chat_response_generation_inactive": voice_intent_chat["chat_response_generation_active"] is False,
            "permission_required_before_voice_chat_handoff": voice_intent_chat["permission_required_before_chat_handoff"] is True,
            "human_confirmation_required_for_action_intent": voice_intent_chat["human_confirmation_required_for_action_intent"] is True,
            "voice_transcript_persistence_disabled": voice_intent_chat["transcript_persistence_enabled"] is False,
            "voice_memory_write_inactive": voice_intent_chat["memory_write_active"] is False,
            "voice_direct_action_disabled": voice_intent_chat["direct_voice_to_action_enabled"] is False,
            "voice_tool_execution_inactive": voice_intent_chat["tool_execution_active"] is False,
            "voice_command_execution_inactive": voice_intent_chat["command_execution_active"] is False,
            "voice_file_mutation_inactive": voice_intent_chat["file_mutation_active"] is False,
            "voice_desktop_action_inactive": voice_intent_chat["desktop_action_active"] is False,
            "voice_network_action_inactive": voice_intent_chat["network_action_active"] is False,
            "voice_git_action_inactive": voice_intent_chat["git_action_active"] is False,
            "voice_stt_runtime_inactive_for_intent": voice_intent_chat["stt_runtime_active"] is False,
            "voice_transcription_inactive_for_intent": voice_intent_chat["transcription_active"] is False,
            "voice_live_microphone_transcription_inactive": voice_intent_chat["live_microphone_transcription_active"] is False,
            "voice_tts_runtime_inactive_for_intent": voice_intent_chat["tts_runtime_active"] is False,
            "voice_speaker_playback_inactive_for_intent": voice_intent_chat["speaker_playback_active"] is False,
            "voice_cloud_stt_fallback_disabled": voice_intent_chat["cloud_stt_fallback_enabled"] is False,
            "voice_silent_cloud_fallback_disabled": voice_intent_chat["silent_cloud_fallback_enabled"] is False,
            "tts_adapter_contract_ready": tts_adapter["tts_adapter_contract_ready"] is True,
            "tts_adapter_runtime_not_ready": tts_adapter["tts_adapter_runtime_ready"] is False,
            "tts_default_adapter_is_piper": tts_adapter["default_adapter"] == "piper",
            "tts_candidate_adapter_count_matches": tts_adapter["candidate_adapter_count"] == len(self.tts_candidates()),
            "tts_local_first_required": tts_adapter["local_first_required"] is True,
            "tts_offline_first_required": tts_adapter["offline_first_required"] is True,
            "voice_response_input_boundary_ready": tts_adapter["voice_response_input_boundary_ready"] is True,
            "future_text_required_for_tts_dry_run": tts_adapter["provided_text_required_for_future_dry_run"] is True,
            "dummy_text_allowed_for_tts_contract": tts_adapter["dummy_text_allowed_for_contract"] is True,
            "tts_text_normalization_contract_ready": tts_adapter["tts_text_normalization_contract_ready"] is True,
            "tts_synthesis_runtime_not_ready": tts_adapter["tts_synthesis_runtime_ready"] is False,
            "tts_synthesis_runtime_inactive": tts_adapter["tts_synthesis_runtime_active"] is False,
            "audio_output_file_boundary_ready": tts_adapter["audio_output_file_boundary_ready"] is True,
            "tts_audio_output_file_write_inactive": tts_adapter["audio_output_file_write_active"] is False,
            "tts_audio_output_file_read_inactive": tts_adapter["audio_output_file_read_active"] is False,
            "tts_audio_file_persistence_disabled": tts_adapter["audio_file_persistence_enabled"] is False,
            "speaker_playback_permission_required": tts_adapter["speaker_playback_permission_required"] is True,
            "tts_speaker_permission_reuses_existing_action": tts_adapter["speaker_permission_action"] == "speaker_speak",
            "speaker_playback_runtime_not_ready": tts_adapter["speaker_playback_runtime_ready"] is False,
            "tts_speaker_playback_inactive": tts_adapter["speaker_playback_active"] is False,
            "audio_playback_device_access_disabled": tts_adapter["audio_playback_device_access"] is False,
            "audio_playback_device_discovery_inactive": tts_adapter["audio_playback_device_discovery_active"] is False,
            "tts_playback_disabled": tts_adapter["playback_enabled"] is False,
            "automatic_speak_after_chat_disabled": tts_adapter["automatic_speak_after_chat_enabled"] is False,
            "voice_response_playback_inactive": tts_adapter["voice_response_playback_active"] is False,
            "chat_response_to_tts_handoff_contract_ready": tts_adapter["chat_response_to_tts_handoff_contract_ready"] is True,
            "chat_response_to_tts_handoff_inactive": tts_adapter["chat_response_to_tts_handoff_active"] is False,
            "tts_model_download_not_required": tts_adapter["model_download_required"] is False,
            "tts_model_download_not_performed": tts_adapter["model_download_performed"] is False,
            "tts_dependency_install_not_performed": tts_adapter["dependency_install_performed"] is False,
            "cloud_tts_fallback_disabled": tts_adapter["cloud_tts_fallback_enabled"] is False,
            "silent_cloud_tts_fallback_disabled": tts_adapter["silent_cloud_fallback_enabled"] is False,
            "remote_tts_provider_disabled": tts_adapter["remote_tts_provider_enabled"] is False,
            "tts_stt_runtime_inactive": tts_adapter["stt_runtime_active"] is False,
            "tts_transcription_inactive": tts_adapter["transcription_active"] is False,
            "tts_microphone_capture_inactive": tts_adapter["microphone_capture_active"] is False,
            "tts_audio_device_access_disabled": tts_adapter["audio_device_access"] is False,
            "tts_audio_buffer_inactive": tts_adapter["audio_buffer_active"] is False,
            "tts_memory_write_inactive": tts_adapter["memory_write_active"] is False,
            "tts_direct_voice_action_disabled": tts_adapter["direct_voice_to_action_enabled"] is False,
            "tts_tool_execution_inactive": tts_adapter["tool_execution_active"] is False,
            "tts_command_execution_inactive": tts_adapter["command_execution_active"] is False,
            "tts_file_mutation_inactive": tts_adapter["file_mutation_active"] is False,
            "tts_desktop_action_inactive": tts_adapter["desktop_action_active"] is False,
            "tts_network_action_inactive": tts_adapter["network_action_active"] is False,
            "tts_git_action_inactive": tts_adapter["git_action_active"] is False,
            "voice_permission_audit_contract_ready": voice_permission_audit["voice_permission_audit_contract_ready"] is True,
            "voice_permission_audit_runtime_not_ready": voice_permission_audit["voice_permission_audit_runtime_ready"] is False,
            "voice_permission_boundary_ready": voice_permission_audit["permission_boundary_ready"] is True,
            "voice_microphone_permission_linked": voice_permission_audit["microphone_permission_action"] == "microphone_listen",
            "voice_speaker_permission_linked": voice_permission_audit["speaker_permission_action"] == "speaker_speak",
            "voice_microphone_permission_required": voice_permission_audit["microphone_permission_required"] is True,
            "voice_speaker_permission_required": voice_permission_audit["speaker_permission_required"] is True,
            "voice_microphone_permission_allowed": voice_permission_audit["microphone_permission_allowed"] is True,
            "voice_speaker_permission_allowed": voice_permission_audit["speaker_permission_allowed"] is True,
            "voice_microphone_permission_requires_confirmation": voice_permission_audit["microphone_permission_requires_confirmation"] is True,
            "voice_speaker_permission_requires_confirmation": voice_permission_audit["speaker_permission_requires_confirmation"] is True,
            "transcript_chat_handoff_permission_required": voice_permission_audit["transcript_chat_handoff_permission_required"] is True,
            "chat_response_tts_permission_required": voice_permission_audit["chat_response_tts_permission_required"] is True,
            "voice_action_permission_required": voice_permission_audit["voice_action_permission_required"] is True,
            "permission_before_microphone_capture": voice_permission_audit["permission_before_microphone_capture"] is True,
            "permission_before_stt": voice_permission_audit["permission_before_stt"] is True,
            "permission_before_tts": voice_permission_audit["permission_before_tts"] is True,
            "permission_before_speaker_playback": voice_permission_audit["permission_before_speaker_playback"] is True,
            "permission_before_chat_handoff": voice_permission_audit["permission_before_chat_handoff"] is True,
            "human_confirmation_required_for_voice_action_intent": voice_permission_audit["human_confirmation_required_for_voice_action_intent"] is True,
            "voice_audit_event_contract_ready": voice_permission_audit["audit_event_contract_ready"] is True,
            "voice_audit_event_schema_ready": voice_permission_audit["audit_event_schema_ready"] is True,
            "voice_audit_event_types_declared": voice_permission_audit["audit_event_type_count"] == 6,
            "voice_audit_event_redaction_boundary_ready": voice_permission_audit["audit_event_redaction_boundary_ready"] is True,
            "voice_audit_event_local_only_required": voice_permission_audit["audit_event_local_only_required"] is True,
            "voice_audit_event_append_only_boundary_ready": voice_permission_audit["audit_event_append_only_boundary_ready"] is True,
            "voice_audit_write_runtime_not_ready": voice_permission_audit["audit_write_runtime_ready"] is False,
            "voice_audit_write_runtime_inactive": voice_permission_audit["audit_write_runtime_active"] is False,
            "voice_audit_event_persistence_disabled": voice_permission_audit["audit_event_persistence_enabled"] is False,
            "voice_audit_log_append_inactive": voice_permission_audit["audit_log_append_active"] is False,
            "voice_audit_storage_write_inactive": voice_permission_audit["audit_storage_write_active"] is False,
            "voice_audit_dashboard_event_emit_inactive": voice_permission_audit["audit_dashboard_event_emit_active"] is False,
            "voice_audit_redaction_runtime_inactive": voice_permission_audit["audit_redaction_runtime_active"] is False,
            "voice_audit_permission_link_runtime_inactive": voice_permission_audit["audit_permission_link_runtime_active"] is False,
            "voice_review_queue_contract_ready": voice_permission_audit["review_queue_contract_ready"] is True,
            "voice_review_queue_runtime_inactive": voice_permission_audit["review_queue_runtime_active"] is False,
            "voice_recovery_visibility_contract_ready": voice_permission_audit["recovery_visibility_contract_ready"] is True,
            "voice_recovery_action_runtime_inactive": voice_permission_audit["recovery_action_runtime_active"] is False,
            "voice_permission_decision_runtime_inactive": voice_permission_audit["permission_decision_runtime_active"] is False,
            "voice_permission_grant_runtime_inactive": voice_permission_audit["permission_grant_runtime_active"] is False,
            "voice_permission_revoke_runtime_inactive": voice_permission_audit["permission_revoke_runtime_active"] is False,
            "voice_permission_persistence_inactive": voice_permission_audit["permission_persistence_active"] is False,
            "voice_permission_mutation_inactive": voice_permission_audit["permission_mutation_active"] is False,
            "voice_permission_mic_capture_inactive": voice_permission_audit["microphone_capture_active"] is False,
            "voice_permission_stt_runtime_inactive": voice_permission_audit["stt_runtime_active"] is False,
            "voice_permission_transcription_inactive": voice_permission_audit["transcription_active"] is False,
            "voice_permission_tts_runtime_inactive": voice_permission_audit["tts_runtime_active"] is False,
            "voice_permission_speaker_playback_inactive": voice_permission_audit["speaker_playback_active"] is False,
            "voice_permission_audio_device_access_disabled": voice_permission_audit["audio_device_access"] is False,
            "voice_permission_playback_device_access_disabled": voice_permission_audit["playback_device_access"] is False,
            "voice_permission_transcript_chat_handoff_inactive": voice_permission_audit["transcript_to_chat_handoff_active"] is False,
            "voice_permission_chat_response_tts_handoff_inactive": voice_permission_audit["chat_response_to_tts_handoff_active"] is False,
            "voice_permission_memory_write_inactive": voice_permission_audit["memory_write_active"] is False,
            "voice_permission_direct_voice_action_disabled": voice_permission_audit["direct_voice_to_action_enabled"] is False,
            "voice_permission_tool_execution_inactive": voice_permission_audit["tool_execution_active"] is False,
            "voice_permission_command_execution_inactive": voice_permission_audit["command_execution_active"] is False,
            "voice_permission_file_mutation_inactive": voice_permission_audit["file_mutation_active"] is False,
            "voice_permission_desktop_action_inactive": voice_permission_audit["desktop_action_active"] is False,
            "voice_permission_network_action_inactive": voice_permission_audit["network_action_active"] is False,
            "voice_permission_git_action_inactive": voice_permission_audit["git_action_active"] is False,
            "voice_permission_cloud_stt_fallback_disabled": voice_permission_audit["cloud_stt_fallback_enabled"] is False,
            "voice_permission_cloud_tts_fallback_disabled": voice_permission_audit["cloud_tts_fallback_enabled"] is False,
            "voice_permission_silent_cloud_fallback_disabled": voice_permission_audit["silent_cloud_fallback_enabled"] is False,
        }

        failed_assertions = [
            name
            for name, passed in assertions.items()
            if not passed
        ]

        return {
            "status": "checked" if not failed_assertions else "failed",
            "runtime_ready": False,
            "planning_ready": True,
            "activation_foundation_ready": activation["activation_foundation_ready"],
            "assertion_count": len(assertions),
            "failed_assertion_count": len(failed_assertions),
            "failed_assertions": failed_assertions,
            "assertions": assertions,
            "python_packages_installed": installed_python,
            "python_packages_total": len(dependencies["python_packages"]),
            "executables_found": found_executables,
            "executables_total": len(dependencies["executables"]),
            "dependencies": dependencies,
            "activation_contract": activation,
            "listen_state_contract": listen_state,
            "microphone_capture_boundary_contract": microphone_boundary,
            "speech_to_text_adapter_runtime_contract": stt_adapter,
            "voice_intent_chat_integration_contract": voice_intent_chat,
            "text_to_speech_adapter_runtime_contract": tts_adapter,
            "voice_permission_audit_runtime_contract": voice_permission_audit,
            "note": "Runtime is not enabled yet. This check did not grant permissions, mutate permission state, write audit events, access microphone/speaker/playback devices, use STT/TTS models, cloud STT/TTS, transcript chat handoff, tools, commands, memory, files, or voice actions.",
        }
